import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Header & Navigation
    'nav.home': 'Home',
    'nav.knowledge': 'Centro de Conhecimento',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Serviços',
    'nav.tools': 'Ferramentas',
    'nav.consumer': 'Minha Área',
    'nav.dashboard': 'Minha Área',
    'header.search': 'Buscar...',
    'header.start': 'Começar',
    'header.login': 'Login',
    'header.signup': 'Cadastro',
    'header.logout': 'Sair',
    'header.profile': 'Perfil',
    'header.language': 'Idioma',

    // Hero Section
    'hero.tagline': 'Melhorando a Segurança Alimentar e Segurança Alimentar',
    'hero.title': 'FOOD SHIELD',
    'hero.description': 'A plataforma completa para transformar sistemas alimentares e promover práticas sustentáveis em Moçambique e além',
    'hero.explore': 'Explorar Plataforma',
    'hero.learn_more': 'Saiba Mais',

    // Features Section
    'features.title': 'Tudo Que Você Precisa',
    'features.subtitle': 'Uma plataforma integrada com ferramentas, conhecimento e recursos para impulsionar a sustentabilidade',
    'features.knowledge': 'Centro de Conhecimento',
    'features.knowledge_desc': 'Biblioteca digital com artigos, vídeos, guias e pesquisas sobre agricultura sustentável',
    'features.marketplace': 'Marketplace',
    'features.marketplace_desc': 'Produtos locais com indicadores de sustentabilidade e impacto ambiental',
    'features.consulting': 'Consultoria',
    'features.consulting_desc': 'Especialistas disponíveis para orientar projetos sustentáveis',
    'features.tools': 'Ferramentas Digitais',
    'features.tools_desc': 'Calculadoras e dashboards para análise de sustentabilidade e custos',

    // Stats Section
    'stats.resources': 'Recursos Disponíveis',
    'stats.users': 'Usuários Ativos',
    'stats.specialists': 'Especialistas',
    'stats.satisfaction': 'Satisfação',

    // CTA Section
    'cta.title': 'Pronto Para Começar?',
    'cta.subtitle': 'Junte-se à nossa comunidade e faça parte da transformação sustentável',
    'cta.button': 'Começar Agora',

    // Newsletter Section
    'newsletter.title': 'Fique Atualizado',
    'newsletter.subtitle': 'Receba dicas, notícias e ofertas exclusivas sobre agricultura sustentável',
    'newsletter.email': 'Seu email...',
    'newsletter.subscribe': 'Inscrever',

    // Footer
    'footer.platform': 'Plataforma',
    'footer.resources': 'Recursos',
    'footer.contact': 'Contato',
    'footer.email': 'Email',
    'footer.phone': 'Telefone',
    'footer.location': 'Localização',
    'footer.company': 'Empresa',
    'footer.about': 'Sobre Nós',
    'footer.team': 'Equipe',
    'footer.careers': 'Carreiras',
    'footer.partners': 'Parceiros',
    'footer.press': 'Imprensa',
    'footer.rights': 'Todos os direitos reservados',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.cookies': 'Cookies',
    'footer.accessibility': 'Acessibilidade',
    'footer.back_to_top': 'Voltar ao topo',

    // Auth
    'auth.login_required': 'Faça login para acessar este recurso',
    'auth.restricted': 'Acesso Restrito',
    'auth.login': 'Fazer Login',
    'auth.signup': 'Cadastrar',
    'auth.welcome_back': 'Bem-vindo de volta',
    'auth.create_account': 'Crie sua conta',
    'auth.email': 'Email',
    'auth.password': 'Senha',
    'auth.confirm_password': 'Confirmar Senha',
    'auth.email_placeholder': 'seu@email.com',
    'auth.password_placeholder': 'Digite sua senha',
    'auth.confirm_password_placeholder': 'Confirme sua senha',
    'auth.or': 'OU',
    'auth.google_login': 'Continuar com Google',
    'auth.no_account': 'Não tem conta? Cadastre-se',
    'auth.have_account': 'Já tem conta? Faça login',
    'auth.fill_all_fields': 'Preencha todos os campos',
    'auth.passwords_dont_match': 'As senhas não coincidem',
    'auth.login_success': 'Login realizado com sucesso!',
    'auth.signup_success': 'Cadastro realizado com sucesso!',
    'auth.error': 'Erro ao autenticar',
    'auth.forgot_password': 'Esqueceu a senha?',
    'auth.reset_password_instructions': 'Digite seu email acima e clique para receber um link de redefinição de senha.',
    'auth.send_reset_email': 'Enviar Email de Redefinição',
    'auth.enter_email_reset': 'Digite seu email para redefinir a senha',
    'auth.reset_email_sent': 'Email de redefinição enviado! Verifique sua caixa de entrada.',

    // Pages
    'page.access_denied': 'Acesso Restrito',
    'page.access_denied_msg': 'Você precisa estar autenticado para acessar esta página.',
    'page.not_found': 'Página Não Encontrada',
    'page.not_found_msg': 'A página que você procura não existe.',

    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Artigos e notícias sobre agricultura sustentável',
    'blog.search_placeholder': 'Buscar artigos...',
    'blog.all_categories': 'Todos',
    'blog.no_results': 'Nenhum artigo encontrado',
    'blog.read_more': 'Ler Mais',
    'blog.by_author': 'Por',
    'blog.read_time': 'min de leitura',

    // Knowledge Center
    'knowledge.title': 'Centro de Conhecimento',
    'knowledge.subtitle': 'Biblioteca digital com recursos sobre agricultura sustentável',
    'knowledge.search_placeholder': 'Buscar recursos...',
    'knowledge.all': 'Todos',
    'knowledge.no_results': 'Nenhum resultado encontrado',

    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.subtitle': 'Produtos locais com indicadores de sustentabilidade',
    'marketplace.filter': 'Filtrar por categoria',
    'marketplace.add_to_cart': 'Adicionar ao Carrinho',
    'marketplace.price': 'Preço',
    'marketplace.stock': 'Em Estoque',
    'marketplace.sustainability': 'Sustentabilidade',
    'marketplace.checkout': 'Finalizar Compra',
    'marketplace.cart_empty': 'Seu carrinho está vazio',
    'marketplace.cart_items': 'itens no carrinho',
    'marketplace.category_all': 'Todos',
    'marketplace.category_seeds': 'Sementes',
    'marketplace.category_inputs': 'Insumos',
    'marketplace.category_equipment': 'Equipamentos',
    'marketplace.category_fresh': 'Produtos Frescos',

    // Services
    'services.title': 'Consultoria',
    'services.subtitle': 'Especialistas disponíveis para orientar seus projetos',
    'services.request': 'Solicitar Consultoria',
    'services.price': 'Preço',
    'services.features': 'Características',
    'services.schedule': 'Agendar Reunião',

    // Tools
    'tools.title': 'Ferramentas Digitais',
    'tools.subtitle': 'Calculadoras e dashboards para análise de sustentabilidade',
    'tools.carbon_calculator': 'Calculadora de Carbono',
    'tools.cost_calculator': 'Calculadora de Custos',
    'tools.calculate': 'Calcular',
    'tools.result': 'Resultado',
    'tools.area_hectares': 'Área (hectares)',
    'tools.fuel_liters': 'Combustível (litros/mês)',
    'tools.fertilizer_kg': 'Fertilizante (kg/mês)',
    'tools.carbon_equivalent': 'Equivalente a:',
    'tools.cost_per_hectare': 'Custo por hectare:',
    'tools.suggested_margin': 'Margem sugerida:',

    // Dashboard
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.activity_summary': 'Aqui está um resumo da sua atividade na plataforma',
    'dashboard.overview': 'Visão Geral',
    'dashboard.purchases': 'Compras',
    'dashboard.consultations': 'Consultorías',
    'dashboard.articles_read': 'Artigos Lidos',
    'dashboard.tools_used': 'Ferramentas Usadas',
    'dashboard.total_spent': 'Total Gasto',
    'dashboard.sustainability_score': 'Pontuação de Sustentabilidade',
    'dashboard.recent_purchases': 'Compras Recentes',
    'dashboard.status_delivered': 'Entregue',
    'dashboard.status_pending': 'Pendente',
    'dashboard.status_scheduled': 'Agendada',
    'dashboard.logout': 'Sair',

    // FAQ
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Encontre respostas para as dúvidas mais comuns sobre o SustainHub',
    'faq.no_answer': 'Não encontrou sua resposta?',
    'faq.contact_us': 'Entre em contato conosco',
    'faq.category.general': 'Geral',
    'faq.category.features': 'Funcionalidades',
    'faq.category.account': 'Conta e Segurança',
    'faq.category.payments': 'Pagamentos',
    'faq.category.support': 'Suporte',
    'faq.q1': 'O que é o SustainHub?',
    'faq.a1': 'SustainHub é uma plataforma completa dedicada à segurança alimentar e desenvolvimento sustentável. Oferecemos ferramentas, conhecimento e recursos para ajudar produtores e empreendedores a implementar práticas sustentáveis em seus negócios.',
    'faq.q2': 'Quem pode usar a plataforma?',
    'faq.a2': 'Qualquer pessoa interessada em agricultura sustentável, segurança alimentar ou desenvolvimento sustentável pode usar o SustainHub. Isso inclui pequenos produtores, cooperativas, consultores, pesquisadores e consumidores conscientes.',
    'faq.q3': 'A plataforma é gratuita?',
    'faq.a3': 'SustainHub oferece um plano gratuito com acesso a recursos básicos. Também temos planos premium com acesso a ferramentas avançadas, consultoria especializada e conteúdo exclusivo.',
    'faq.q4': 'Como funciona o Centro de Conhecimento?',
    'faq.a4': 'O Centro de Conhecimento é uma biblioteca digital com artigos, vídeos, guias e pesquisas sobre agricultura sustentável. Você pode buscar por tópicos, filtrar por categoria e acessar conteúdo de especialistas.',
    'faq.q5': 'O que é o Marketplace?',
    'faq.a5': 'O Marketplace é um espaço onde produtores locais podem vender produtos sustentáveis diretamente aos consumidores. Todos os produtos têm indicadores de impacto ambiental e informações de origem.',
    'faq.q6': 'Como solicitar consultoria?',
    'faq.a6': 'Na seção de Serviços, você pode visualizar consultores disponíveis e suas especialidades. Clique em \'Solicitar Consultoria\', preencha o formulário com seus detalhes e um consultor entrará em contato em breve.',
    'faq.q7': 'Quais são as ferramentas disponíveis?',
    'faq.a7': 'Oferecemos calculadoras de emissões de carbono, análise de custos de produção, calculadora nutricional e dashboards para monitorar sustentabilidade. Mais ferramentas estão sendo desenvolvidas continuamente.',
    'faq.q8': 'Como criar uma conta?',
    'faq.a8': 'Clique no botão \'Criar Conta\' na página inicial, preencha seus dados (nome, email e senha) e confirme seu email. Sua conta estará pronta para usar imediatamente.',
    'faq.q9': 'Meus dados estão seguros?',
    'faq.a9': 'Sim, utilizamos criptografia de ponta a ponta e seguimos as melhores práticas de segurança de dados. Seus dados pessoais nunca são compartilhados com terceiros sem seu consentimento.',
    'faq.q10': 'Como faço para recuperar minha senha?',
    'faq.a10': 'Na página de login, clique em \'Esqueceu a senha?\'. Insira seu email e receberá um link para redefinir sua senha. O link é válido por 24 horas.',
    'faq.q11': 'Posso deletar minha conta?',
    'faq.a11': 'Sim, você pode deletar sua conta a qualquer momento nas configurações de perfil. Todos os seus dados serão removidos permanentemente após 30 dias.',
    'faq.q12': 'Quais são os planos disponíveis?',
    'faq.a12': 'Oferecemos 3 planos: Gratuito (recursos básicos), Premium (ferramentas avançadas) e Empresarial (consultoria dedicada). Cada plano pode ser cancelado a qualquer momento.',
    'faq.q13': 'Como faço para fazer upgrade?',
    'faq.a13': 'Na sua conta, acesse \'Planos e Assinatura\' e selecione o plano desejado. Você será redirecionado para a página de pagamento segura. O upgrade é imediato após o pagamento.',
    'faq.q14': 'Vocês oferecem reembolso?',
    'faq.a14': 'Sim, oferecemos garantia de 30 dias. Se não estiver satisfeito, você pode solicitar reembolso total dentro desse período, sem perguntas.',
    'faq.q15': 'Quais formas de pagamento vocês aceitam?',
    'faq.a15': 'Aceitamos cartão de crédito, transferência bancária e carteiras digitais. Todos os pagamentos são processados através de gateways seguros e certificados.',
    'faq.q16': 'Como entro em contato com o suporte?',
    'faq.a16': 'Você pode entrar em contato através do formulário de contato no site, enviar email para support@sustainhub.com ou usar o chat ao vivo disponível 24/7.',
    'faq.q17': 'Qual é o tempo de resposta do suporte?',
    'faq.a17': 'Respondemos a todas as mensagens dentro de 24 horas. Para questões urgentes, use o chat ao vivo que está disponível durante o horário comercial.',
    'faq.q18': 'Vocês oferecem treinamento?',
    'faq.a18': 'Sim, oferecemos webinars gratuitos, tutoriais em vídeo e documentação completa. Clientes premium também têm acesso a treinamento personalizado.',

    // Admin Dashboard
    'admin.title': 'Painel de Administração',
    'admin.overview': 'Visão Geral',
    'admin.users': 'Usuários',
    'admin.blog': 'Blog',
    'admin.marketplace': 'Marketplace',
    'admin.products': 'Produtos',
    'admin.orders': 'Pedidos',
    'admin.services': 'Serviços',
    'admin.reports': 'Relatórios',
    'admin.settings': 'Configurações',
    'admin.access_denied': 'Acesso Restrito',
    'admin.access_denied_msg': 'Apenas administradores podem acessar este painel.',
    'admin.logged_in_as': 'Conectado como',
    'admin.total_users': 'Total de Usuários',
    'admin.registered': 'Registrados',
    'admin.blog_articles': 'Artigos de Blog',
    'admin.published': 'Publicados',
    'admin.in_marketplace': 'No Marketplace',
    'admin.services_available': 'Serviços',
    'admin.available': 'Disponíveis',
    'admin.manage_users': 'Gerenciar Usuários',
    'admin.new_user': 'Novo Usuário',
    'admin.manage_blog': 'Gerenciar Blog',
    'admin.new_article': 'Novo Artigo',
    'admin.manage_marketplace': 'Gerenciar Marketplace',
    'admin.manage_services': 'Gerenciar Serviços',
    'admin.reports_analytics': 'Relatórios e Analytics',
    'admin.search_by_name': 'Buscar por nome ou email...',
    'admin.search_articles': 'Buscar artigos...',
    'admin.per_page': 'por página',
    'admin.showing': 'Mostrando',
    'admin.of': 'de',
    'admin.name': 'Nome',
    'admin.email': 'Email',
    'admin.role': 'Função',
    'admin.actions': 'Ações',
    'admin.title_col': 'Título',
    'admin.author': 'Autor',
    'admin.status': 'Status',
    'admin.user': 'Usuário',
    'admin.admin': 'Admin',
    'admin.draft': 'Rascunho',
    'admin.published_status': 'Publicado',
    'admin.confirm_delete': 'Tem certeza?',
    'admin.new_user_modal': 'Novo Usuário',
    'admin.edit_user_modal': 'Editar Usuário',
    'admin.full_name': 'Nome completo',
    'admin.user_role': 'Função',
    'admin.new_article_modal': 'Novo Artigo',
    'admin.title_pt': 'Título (PT)',
    'admin.title_en': 'Título (EN)',
    'admin.excerpt_pt': 'Resumo (PT)',
    'admin.excerpt_en': 'Resumo (EN)',
    'admin.content_pt': 'Conteúdo (PT)',
    'admin.content_en': 'Conteúdo (EN)',
    'admin.category': 'Categoria',
    'admin.image_url': 'URL da Imagem',
    'admin.read_time': 'Tempo de Leitura (min)',
    'admin.article_status': 'Status',
    'admin.visitors_per_month': 'Visitantes por Mês',
    'admin.visitor_chart': 'Gráfico de visitantes',
    'admin.sales_by_product': 'Vendas por Produto',
    'admin.sales_chart': 'Gráfico de vendas',
    'admin.platform_name': 'Nome da Plataforma',
    'admin.contact_email': 'Email de Contato',
    'admin.save_changes': 'Salvar Alterações',
    'admin.coming_soon': 'Em desenvolvimento...',

    // Common
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.view_all': 'Ver Todas',
    'common.learn_more': 'Saiba Mais',
    'common.get_started': 'Começar',
    'common.subscribe': 'Inscrever',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.delete': 'Deletar',
    'common.edit': 'Editar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    
    // Reviews
    'reviews.error_submit': 'Erro ao enviar avaliação',
    'reviews.login_required': 'Faça login para avaliar',
    'reviews.rating_required': 'Selecione uma classificação',
    
    // Categories
    'category.seeds': 'Sementes',
    'category.inputs': 'Insumos',
    'category.equipment': 'Equipamentos',
    'common.info': 'Informação',
    'common.no_results': 'Nenhum resultado encontrado para',

    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.delivery_info': 'Informações de Entrega',
    'checkout.address': 'Endereço',
    'checkout.address_placeholder': 'Rua, número, bairro...',
    'checkout.city': 'Cidade',
    'checkout.city_placeholder': 'Maputo',
    'checkout.phone': 'Telefone',
    'checkout.notes': 'Observações',
    'checkout.notes_placeholder': 'Instruções adicionais para entrega...',
    'checkout.payment_method': 'Método de Pagamento',
    'checkout.cash_on_delivery': 'Pagamento na Entrega',
    'checkout.bank_transfer': 'Transferência Bancária',
    'checkout.place_order': 'Confirmar Pedido',
    'checkout.processing': 'Processando...',
    'checkout.order_summary': 'Resumo do Pedido',
    'checkout.total': 'Total',
    'checkout.success': 'Pedido realizado com sucesso!',
    'checkout.error': 'Erro ao processar pedido',
    'checkout.empty_cart': 'Carrinho Vazio',
    'checkout.add_products': 'Adicione produtos ao carrinho para continuar',
    'checkout.go_marketplace': 'Ir para Marketplace',
    'checkout.fill_required': 'Preencha todos os campos obrigatórios',
    'checkout.payment.cash': 'Dinheiro',
    'checkout.payment.bank_transfer': 'Transferência Bancária',

    // Orders
    'orders.my_orders': 'Meus Pedidos',
    'orders.order': 'Pedido',
    'orders.no_orders': 'Nenhum Pedido',
    'orders.start_shopping': 'Comece a comprar para ver seus pedidos aqui',
    'orders.login_required': 'Login Necessário',
    'orders.login_to_view': 'Faça login para ver seus pedidos',
    'orders.delivery_address': 'Endereço de Entrega',
    'orders.payment_method': 'Método de Pagamento',
    'orders.notes': 'Observações',
    'orders.status.pending': 'Pendente',
    'orders.status.processing': 'Processando',
    'orders.status.shipped': 'Enviado',
    'orders.status.delivered': 'Entregue',
    'orders.status.cancelled': 'Cancelado',
    'myArea.title': 'Minha Área',
    'myArea.welcome': 'Bem-vindo',
    'myArea.orders': 'Pedidos',
    'myArea.profile': 'Perfil',
    'myArea.myOrders': 'Meus Pedidos',
    'myArea.ordersDescription': 'Veja o histórico dos seus pedidos',
    'myArea.order': 'Pedido',
    'myArea.status.pending': 'Pendente',
    'myArea.status.processing': 'Em Processamento',
    'myArea.status.shipped': 'Enviado',
    'myArea.status.delivered': 'Entregue',
    'myArea.status.cancelled': 'Cancelado',
    'myArea.deliveryAddress': 'Endereço de Entrega',
    'myArea.phone': 'Telefone',
    'myArea.paymentMethod': 'Método de Pagamento',
    'myArea.noOrders': 'Você ainda não fez nenhum pedido',
    'myArea.goToMarketplace': 'Ir para o Marketplace',
    'myArea.profileInfo': 'Informações do Perfil',
    'myArea.profileDescription': 'Gerencie suas informações pessoais',
    'myArea.name': 'Nome',
    'myArea.email': 'Email',
    'myArea.loginMethod': 'Método de Login',
    'myArea.memberSince': 'Membro desde',

    // Consumer Area
    'consumer.title': 'Minha Área',
    'consumer.dashboard': 'Dashboard',
    'consumer.blog': 'Blog',
    'consumer.knowledge': 'Centro de Conhecimento',
    'consumer.tools': 'Ferramentas',
    'consumer.marketplace': 'Marketplace',
    'consumer.services': 'Serviços',
    'consumer.profile': 'Perfil',
    'consumer.notifications': 'Notificações',
    'consumer.logout': 'Sair',
    'consumer.editProfile': 'Editar Perfil',
    'consumer.profileDesc': 'Gerencie suas informações pessoais',
    'consumer.profilePicture': 'Foto de Perfil',
    'consumer.changePhoto': 'Alterar Foto',
    'consumer.personalInfo': 'Informações Pessoais',
    'consumer.personalInfoDesc': 'Atualize seus dados pessoais',
    'consumer.name': 'Nome',
    'consumer.email': 'Email',
    'consumer.phone': 'Telefone',
    'consumer.address': 'Endereço',
    'consumer.bio': 'Sobre Mim',
    'consumer.saveChanges': 'Salvar Alterações',
    'consumer.cancel': 'Cancelar',
    'consumer.notificationPreferences': 'Preferências de Notificação',
    'consumer.notificationPreferencesDesc': 'Gerencie como você recebe notificações',
    'consumer.emailNotifications': 'Notificações por Email',
    'consumer.emailNotificationsDesc': 'Receber atualizações por email',
    'consumer.orderUpdates': 'Atualizações de Pedidos',
    'consumer.orderUpdatesDesc': 'Notificações sobre status de pedidos',
    'consumer.promotions': 'Promoções e Ofertas',
    'consumer.promotionsDesc': 'Receber ofertas especiais e promoções',
    'consumer.profileUpdated': 'Perfil atualizado com sucesso',
    'consumer.nameReadOnly': 'Nome não pode ser alterado',
    'consumer.emailReadOnly': 'Email não pode ser alterado',
    'consumer.photoUpdated': 'Foto de perfil atualizada com sucesso',
    'consumer.invalidImageType': 'Por favor, selecione um arquivo de imagem válido',
    'consumer.imageTooLarge': 'O tamanho da imagem deve ser menor que 10MB',
    'consumer.compressingImage': 'Comprimindo imagem...',
    'consumer.uploadFailed': 'Falha ao fazer upload da foto',
    'consumer.welcome': 'Bem-vindo de volta!',
    'consumer.welcomeMessage': 'Aqui está um resumo da sua atividade',
    'consumer.stats.orders': 'Pedidos',
    'consumer.stats.articlesRead': 'Artigos Lidos',
    'consumer.stats.services': 'Serviços',
    'consumer.stats.sustainability': 'Sustentabilidade',
    'consumer.recentOrders': 'Pedidos Recentes',
    'consumer.viewAll': 'Ver Todos',
    'consumer.noOrders': 'Você ainda não fez nenhum pedido',
    'consumer.startShopping': 'Começar a Comprar',
    'consumer.order': 'Pedido',
    'consumer.exploreMarketplace': 'Explorar Marketplace',
    'consumer.exploreMarketplaceDesc': 'Descubra produtos sustentáveis',
    'consumer.readArticles': 'Ler Artigos',
    'consumer.readArticlesDesc': 'Aprenda sobre segurança alimentar',
    'consumer.bookService': 'Agendar Serviço',
    'consumer.bookServiceDesc': 'Consultorias especializadas',
    'consumer.favorites': 'Favoritos',

    // Favorites
    'favorites.subtitle': 'Seus produtos e artigos favoritos',
    'favorites.products': 'Produtos Favoritos',
    'favorites.articles': 'Artigos Favoritos',
    'favorites.no_products': 'Você ainda não tem produtos favoritos',
    'favorites.no_articles': 'Você ainda não tem artigos favoritos',
    'favorites.browse_products': 'Explorar Produtos',
    'favorites.browse_articles': 'Explorar Artigos',
    'favorites.removed': 'Removido dos favoritos',
    'favorites.added': 'Adicionado aos favoritos',

    // About Page
    'about.title': 'Sobre Nós',
    'about.subtitle': 'Transformando sistemas alimentares para um futuro sustentável em Moçambique',
    'about.mission': 'Nossa Missão',
    'about.mission_text': 'Promover a segurança alimentar e nutricional em Moçambique através de uma plataforma integrada que conecta produtores, consumidores e especialistas, facilitando o acesso a conhecimento, produtos sustentáveis e serviços de consultoria.',
    'about.vision': 'Nossa Visão',
    'about.vision_text': 'Ser a principal plataforma de transformação de sistemas alimentares em Moçambique, reconhecida pela excelência em promover práticas sustentáveis, inovação tecnológica e impacto social positivo nas comunidades rurais e urbanas.',
    'about.story': 'Nossa História',
    'about.story_p1': 'A SustainHub nasceu da necessidade urgente de abordar os desafios de segurança alimentar em Moçambique. Fundada em 2024, nossa plataforma foi criada por uma equipe de especialistas em agricultura, tecnologia e desenvolvimento sustentável.',
    'about.story_p2': 'Reconhecendo que a segurança alimentar vai além da produção de alimentos, desenvolvemos uma solução holística que integra conhecimento, comércio justo, consultoria especializada e ferramentas digitais para empoderar agricultores e consumidores.',
    'about.story_p3': 'Hoje, servimos milhares de usuários em todo Moçambique, conectando produtores locais a mercados, fornecendo educação sobre práticas sustentáveis e facilitando o acesso a serviços especializados que transformam vidas e comunidades.',
    'about.values_title': 'Nossos Valores',
    'about.values_subtitle': 'Princípios que guiam cada decisão e ação',
    'about.values.sustainability': 'Sustentabilidade',
    'about.values.sustainability_desc': 'Comprometidos com práticas que preservam o meio ambiente e garantem recursos para gerações futuras',
    'about.values.community': 'Comunidade',
    'about.values.community_desc': 'Fortalecemos conexões entre produtores, consumidores e especialistas para criar impacto coletivo',
    'about.values.quality': 'Qualidade',
    'about.values.quality_desc': 'Garantimos excelência em produtos, serviços e conteúdo educacional',
    'about.values.innovation': 'Inovação',
    'about.values.innovation_desc': 'Utilizamos tecnologia e criatividade para resolver desafios complexos de forma eficaz',
    'about.impact': 'Nosso Impacto',
    'about.stats.users': 'Usuários Ativos',
    'about.stats.products': 'Produtos Sustentáveis',
    'about.stats.specialists': 'Especialistas',
    'about.stats.satisfaction': 'Satisfação',
    'about.team': 'Nossa Equipe',
    'about.team_subtitle': 'Profissionais dedicados a transformar sistemas alimentares',
    'about.team_member_1_name': 'Dinis Matavele',
    'about.team_member_1_role': 'CEO & Fundador',
    'about.team_member_1_bio': 'Especialista em segurança alimentar com 10+ anos de experiência em desenvolvimento rural',
    'about.team_member_2_name': 'Ana Silva',
    'about.team_member_2_role': 'Diretora de Tecnologia',
    'about.team_member_2_bio': 'Engenheira de software focada em soluções digitais para agricultura sustentável',
    'about.team_member_3_name': 'Carlos Nhaca',
    'about.team_member_3_role': 'Diretor de Operações',
    'about.team_member_3_bio': 'Agrônomo especializado em práticas sustentáveis e gestão de cadeias de valor',

    // Welcome Page
    'welcome.title': 'Bem-vindo ao SustainHub!',
    'welcome.subtitle': 'Vamos conhecer a plataforma em 4 passos rápidos',
    'welcome.complete': 'Bem-vindo! Explore a plataforma.',
    'welcome.skip': 'Pular',
    'welcome.back': 'Voltar',
    'welcome.next': 'Próximo',
    'welcome.start': 'Começar',
    
    'welcome.step1.title': 'Plataforma Completa de Sustentabilidade',
    'welcome.step1.description': 'SustainHub é o seu hub central para transformar sistemas alimentares e promover práticas sustentáveis em Moçambique.',
    'welcome.step1.feature1': 'Acesso a recursos educacionais e pesquisas',
    'welcome.step1.feature2': 'Conexão com especialistas locais',
    'welcome.step1.feature3': 'Ferramentas de análise e planejamento',
    'welcome.step1.feature4': 'Comunidade ativa de produtores',
    
    'welcome.step2.title': 'Marketplace Sustentável',
    'welcome.step2.description': 'Compre e venda produtos locais com indicadores de sustentabilidade e impacto ambiental transparentes.',
    'welcome.step2.feature1': 'Produtos certificados e rastreáveis',
    'welcome.step2.feature2': 'Indicadores de sustentabilidade',
    'welcome.step2.feature3': 'Preços justos e transparentes',
    'welcome.step2.feature4': 'Entrega rápida e segura',
    
    'welcome.step3.title': 'Centro de Conhecimento',
    'welcome.step3.description': 'Acesse uma biblioteca digital completa com artigos, vídeos, guias práticos e pesquisas sobre agricultura sustentável.',
    'welcome.step3.feature1': 'Artigos técnicos e científicos',
    'welcome.step3.feature2': 'Vídeos tutoriais práticos',
    'welcome.step3.feature3': 'Guias passo a passo',
    'welcome.step3.feature4': 'Pesquisas e estudos de caso',
    
    'welcome.step4.title': 'Ferramentas e Serviços',
    'welcome.step4.description': 'Utilize calculadoras especializadas, dashboards de análise e consulte especialistas para otimizar suas operações.',
    'welcome.step4.feature1': 'Calculadoras de sustentabilidade',
    'welcome.step4.feature2': 'Dashboards de análise',
    'welcome.step4.feature3': 'Consultoria especializada',
    'welcome.step4.feature4': 'Agendamento de serviços',

    // Profile Page
    'profile.title': 'Meu Perfil',
    'profile.subtitle': 'Gerencie suas informações pessoais e preferências',
    'profile.personal_info': 'Informações Pessoais',
    'profile.name': 'Nome',
    'profile.name_placeholder': 'Digite seu nome completo',
    'profile.email': 'Email',
    'profile.phone': 'Telefone',
    'profile.phone_placeholder': '+258 XX XXX XXXX',
    'profile.address': 'Endereço',
    'profile.address_placeholder': 'Digite seu endereço completo',
    'profile.bio': 'Biografia',
    'profile.bio_placeholder': 'Conte um pouco sobre você...',
    'profile.language': 'Idioma',
    'profile.notifications': 'Preferências de Notificações',
    'profile.email_notifications': 'Notificações por Email',
    'profile.email_notifications_desc': 'Receba atualizações importantes por email',
    'profile.order_updates': 'Atualizações de Pedidos',
    'profile.order_updates_desc': 'Receba notificações sobre seus pedidos',
    'profile.promotions': 'Promoções e Ofertas',
    'profile.promotions_desc': 'Receba ofertas especiais e promoções',
    'profile.update_success': 'Perfil atualizado com sucesso!',
    'profile.update_error': 'Erro ao atualizar perfil',
    'profile.upload_photo': 'Enviar Foto',
    'profile.cancel': 'Cancelar',
    'profile.photo_upload_success': 'Foto de perfil atualizada com sucesso!',
    'profile.photo_upload_error': 'Erro ao enviar foto',
    'profile.photo_size_error': 'A foto deve ter no máximo 5MB',
    'profile.photo_type_error': 'Apenas imagens são permitidas',

    // Consumer Area (Public)
    'consumerArea.title': 'Área de Consumidor',
    'consumerArea.subtitle': 'Conteúdo público sobre agricultura sustentável',
    'consumerArea.tabs.blog': 'Blog',
    'consumerArea.tabs.events': 'Eventos',
    'consumerArea.tabs.news': 'Notícias',
    'consumerArea.noBlog': 'Nenhum artigo de blog disponível',
    'consumerArea.noEvents': 'Nenhum evento disponível',
    'consumerArea.noNews': 'Nenhuma notícia disponível',
    'consumerArea.readMore': 'Ler Mais',
    'consumerArea.viewDetails': 'Ver Detalhes',
    'consumerArea.eventDate': 'Data do Evento',
    'consumerArea.eventLocation': 'Local',
    'consumerArea.newsDate': 'Data da Notícia',
    'consumerArea.by': 'Por',
    'consumerArea.category': 'Categoria',

    // Services Page
    'services.service1.title': 'Consultoria Técnica Agrícola',
    'services.service1.description': 'Especialistas em agricultura sustentável para otimizar sua produção',
    'services.service1.feature1': 'Análise de solo',
    'services.service1.feature2': 'Planejamento de cultivo',
    'services.service1.feature3': 'Gestão de recursos',
    'services.service1.price': 'A partir de 2.500 MZN/hora',
    'services.service2.title': 'Assessoria em Sustentabilidade',
    'services.service2.description': 'Desenvolva práticas sustentáveis e certificações ambientais',
    'services.service2.feature1': 'Certificação orgânica',
    'services.service2.feature2': 'Gestão de resíduos',
    'services.service2.feature3': 'Pegada de carbono',
    'services.service2.price': 'A partir de 3.000 MZN/hora',
    'services.service3.title': 'Treinamento e Capacitação',
    'services.service3.description': 'Workshops e cursos práticos para sua equipe',
    'services.service3.feature1': 'Workshops presenciais',
    'services.service3.feature2': 'Cursos online',
    'services.service3.feature3': 'Material didático',
    'services.service3.price': 'A partir de 5.000 MZN/dia',
    'services.service4.title': 'Análise de Mercado',
    'services.service4.description': 'Estudos de viabilidade e estratégias de comercialização',
    'services.service4.feature1': 'Pesquisa de mercado',
    'services.service4.feature2': 'Análise de concorrência',
    'services.service4.feature3': 'Plano de negócios',
    'services.service4.price': 'A partir de 4.000 MZN/projeto',
    'services.schedule_consultation': 'Agendar Consulta',
    'services.need_help': 'Precisa de Ajuda Personalizada?',
    'services.team_ready': 'Nossa equipe está pronta para entender suas necessidades específicas',
    'services.chat_online': 'Chat Online',
    'services.chat_response': 'Resposta em minutos',
    'services.schedule_meeting': 'Agendar Reunião',
    'services.choose_time': 'Escolha melhor horário',
    'services.in_person': 'Visita Presencial',
    'services.on_site': 'Atendimento no local',
    'services.contact_us': 'Entrar em Contato',

    // Tools Page
    'tools.tab_carbon': 'Carbono',
    'tools.tab_cost': 'Custos',
    'tools.tab_nutrition': 'Nutrição',
    'tools.carbon.title': 'Calculadora de Emissões de Carbono',
    'tools.carbon.description': 'Estime as emissões de CO₂ da sua operação agrícola',
    'tools.carbon.area_label': 'Área Cultivada (hectares)',
    'tools.carbon.area_placeholder': 'Ex: 10.5',
    'tools.carbon.fuel_label': 'Combustível Usado (litros/mês)',
    'tools.carbon.fuel_placeholder': 'Ex: 200',
    'tools.carbon.fertilizer_label': 'Fertilizantes (kg/mês)',
    'tools.carbon.fertilizer_placeholder': 'Ex: 150',
    'tools.carbon.calculate': 'Calcular Emissões',
    'tools.carbon.result_title': 'Resultado da Análise',
    'tools.carbon.result_description': 'Suas emissões estimadas de CO₂',
    'tools.carbon.result_value': 'toneladas de CO₂/ano',
    'tools.carbon.result_info': 'Este cálculo é uma estimativa baseada em médias do setor agrícola.',
    'tools.cost.title': 'Análise de Custos de Produção',
    'tools.cost.description': 'Calcule os custos totais da sua operação',
    'tools.cost.seeds_label': 'Custo de Sementes (MZN)',
    'tools.cost.seeds_placeholder': 'Ex: 5000',
    'tools.cost.labor_label': 'Mão de Obra (MZN)',
    'tools.cost.labor_placeholder': 'Ex: 15000',
    'tools.cost.equipment_label': 'Equipamentos (MZN)',
    'tools.cost.equipment_placeholder': 'Ex: 8000',
    'tools.cost.calculate': 'Calcular Custos',
    'tools.cost.result_title': 'Custo Total Estimado',
    'tools.cost.result_description': 'Resumo dos seus custos de produção',
    'tools.cost.result_info': 'Este valor representa o custo total estimado para o período especificado.',
    'tools.nutrition.title': 'Calculadora Nutricional',
    'tools.nutrition.description': 'Analise o valor nutricional dos seus produtos',
    'tools.nutrition.coming_soon': 'Em breve',
    'tools.nutrition.info': 'Esta ferramenta estará disponível em breve para ajudá-lo a calcular o valor nutricional dos seus produtos agrícolas.',
  },
  en: {
    // Header & Navigation
    'nav.home': 'Home',
    'nav.knowledge': 'Knowledge Center',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Services',
    'nav.tools': 'Tools',
    'nav.consumer': 'My Area',
    'nav.dashboard': 'My Area',
    'header.search': 'Search...',
    'header.start': 'Get Started',
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.logout': 'Logout',
    'header.profile': 'Profile',
    'header.language': 'Language',

    // Hero Section
    'hero.tagline': 'Improving Food Safety & Food Security',
    'hero.title': 'FOOD SHIELD',
    'hero.description': 'The complete platform to transform food systems and promote sustainable practices in Mozambique and beyond',
    'hero.explore': 'Explore Platform',
    'hero.learn_more': 'Learn More',

    // Features Section
    'features.title': 'Everything You Need',
    'features.subtitle': 'An integrated platform with tools, knowledge and resources to drive sustainability',
    'features.knowledge': 'Knowledge Center',
    'features.knowledge_desc': 'Digital library with articles, videos, guides and research on sustainable agriculture',
    'features.marketplace': 'Marketplace',
    'features.marketplace_desc': 'Local products with sustainability indicators and environmental impact',
    'features.consulting': 'Consulting',
    'features.consulting_desc': 'Experts available to guide sustainable projects',
    'features.tools': 'Digital Tools',
    'features.tools_desc': 'Calculators and dashboards for sustainability and cost analysis',

    // Stats Section
    'stats.resources': 'Available Resources',
    'stats.users': 'Active Users',
    'stats.specialists': 'Specialists',
    'stats.satisfaction': 'Satisfaction',

    // CTA Section
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Join our community and be part of the sustainable transformation',
    'cta.button': 'Get Started Now',

    // Newsletter Section
    'newsletter.title': 'Stay Updated',
    'newsletter.subtitle': 'Get tips, news and exclusive offers about sustainable agriculture',
    'newsletter.email': 'Your email...',
    'newsletter.subscribe': 'Subscribe',

    // Footer
    'footer.platform': 'Platform',
    'footer.resources': 'Resources',
    'footer.contact': 'Contact',
    'footer.email': 'Email',
    'footer.phone': 'Phone',
    'footer.location': 'Location',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.team': 'Team',
    'footer.careers': 'Careers',
    'footer.partners': 'Partners',
    'footer.press': 'Press',
    'footer.rights': 'All rights reserved',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookies',
    'footer.accessibility': 'Accessibility',
    'footer.back_to_top': 'Back to top',

    // Auth
    'auth.login_required': 'Login to access this resource',
    'auth.restricted': 'Access Restricted',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.welcome_back': 'Welcome back',
    'auth.create_account': 'Create your account',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.email_placeholder': 'your@email.com',
    'auth.password_placeholder': 'Enter your password',
    'auth.confirm_password_placeholder': 'Confirm your password',
    'auth.or': 'OR',
    'auth.google_login': 'Continue with Google',
    'auth.no_account': 'No account? Sign up',
    'auth.have_account': 'Already have an account? Login',
    'auth.fill_all_fields': 'Fill in all fields',
    'auth.passwords_dont_match': 'Passwords do not match',
    'auth.login_success': 'Login successful!',
    'auth.signup_success': 'Sign up successful!',
    'auth.error': 'Authentication error',
    'auth.forgot_password': 'Forgot password?',
    'auth.reset_password_instructions': 'Enter your email above and click to receive a password reset link.',
    'auth.send_reset_email': 'Send Reset Email',
    'auth.enter_email_reset': 'Enter your email to reset password',
    'auth.reset_email_sent': 'Reset email sent! Check your inbox.',

    // Pages
    'page.access_denied': 'Access Restricted',
    'page.access_denied_msg': 'You need to be authenticated to access this page.',
    'page.not_found': 'Page Not Found',
    'page.not_found_msg': 'The page you are looking for does not exist.',

    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Articles and news about sustainable agriculture',
    'blog.search_placeholder': 'Search articles...',
    'blog.all_categories': 'All',
    'blog.no_results': 'No articles found',
    'blog.read_more': 'Read More',
    'blog.by_author': 'By',
    'blog.read_time': 'min read',

    // Knowledge Center
    'knowledge.title': 'Knowledge Center',
    'knowledge.subtitle': 'Digital library with resources on sustainable agriculture',
    'knowledge.search_placeholder': 'Search resources...',
    'knowledge.all': 'All',
    'knowledge.no_results': 'No results found',

    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.subtitle': 'Local products with sustainability indicators',
    'marketplace.filter': 'Filter by category',
    'marketplace.add_to_cart': 'Add to Cart',
    'marketplace.price': 'Price',
    'marketplace.stock': 'In Stock',
    'marketplace.sustainability': 'Sustainability',
    'marketplace.checkout': 'Checkout',
    'marketplace.cart_empty': 'Your cart is empty',
    'marketplace.cart_items': 'items in cart',
    'marketplace.category_all': 'All',
    'marketplace.category_seeds': 'Seeds',
    'marketplace.category_inputs': 'Inputs',
    'marketplace.category_equipment': 'Equipment',
    'marketplace.category_fresh': 'Fresh Products',

    // Services
    'services.title': 'Consulting',
    'services.subtitle': 'Experts available to guide your projects',
    'services.request': 'Request Consulting',
    'services.price': 'Price',
    'services.features': 'Features',
    'services.schedule': 'Schedule Meeting',

    // Tools
    'tools.title': 'Digital Tools',
    'tools.subtitle': 'Calculators and dashboards for sustainability analysis',
    'tools.carbon_calculator': 'Carbon Calculator',
    'tools.cost_calculator': 'Cost Calculator',
    'tools.calculate': 'Calculate',
    'tools.result': 'Result',
    'tools.area_hectares': 'Area (hectares)',
    'tools.fuel_liters': 'Fuel (liters/month)',
    'tools.fertilizer_kg': 'Fertilizer (kg/month)',
    'tools.carbon_equivalent': 'Equivalent to:',
    'tools.cost_per_hectare': 'Cost per hectare:',
    'tools.suggested_margin': 'Suggested margin:',

    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.activity_summary': 'Here is a summary of your activity on the platform',
    'dashboard.overview': 'Overview',
    'dashboard.purchases': 'Purchases',
    'dashboard.consultations': 'Consultations',
    'dashboard.articles_read': 'Articles Read',
    'dashboard.tools_used': 'Tools Used',
    'dashboard.total_spent': 'Total Spent',
    'dashboard.sustainability_score': 'Sustainability Score',
    'dashboard.recent_purchases': 'Recent Purchases',
    'dashboard.status_delivered': 'Delivered',
    'dashboard.status_pending': 'Pending',
    'dashboard.status_scheduled': 'Scheduled',
    'dashboard.logout': 'Logout',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about SustainHub',
    'faq.no_answer': 'Did not find your answer?',
    'faq.contact_us': 'Contact us',
    'faq.category.general': 'General',
    'faq.category.features': 'Features',
    'faq.category.account': 'Account & Security',
    'faq.category.payments': 'Payments',
    'faq.category.support': 'Support',
    'faq.q1': 'What is SustainHub?',
    'faq.a1': 'SustainHub is a complete platform dedicated to food safety and sustainable development. We offer tools, knowledge, and resources to help producers and entrepreneurs implement sustainable practices in their businesses.',
    'faq.q2': 'Who can use the platform?',
    'faq.a2': 'Anyone interested in sustainable agriculture, food security, or sustainable development can use SustainHub. This includes small producers, cooperatives, consultants, researchers, and conscious consumers.',
    'faq.q3': 'Is the platform free?',
    'faq.a3': 'SustainHub offers a free plan with access to basic resources. We also have premium plans with access to advanced tools, specialized consulting, and exclusive content.',
    'faq.q4': 'How does the Knowledge Center work?',
    'faq.a4': 'The Knowledge Center is a digital library with articles, videos, guides, and research on sustainable agriculture. You can search by topics, filter by category, and access expert content.',
    'faq.q5': 'What is the Marketplace?',
    'faq.a5': 'The Marketplace is a space where local producers can sell sustainable products directly to consumers. All products have environmental impact indicators and origin information.',
    'faq.q6': 'How do I request consulting?',
    'faq.a6': 'In the Services section, you can view available consultants and their specialties. Click \'Request Consulting\', fill out the form with your details, and a consultant will contact you soon.',
    'faq.q7': 'What tools are available?',
    'faq.a7': 'We offer carbon emissions calculators, production cost analysis, nutritional calculator, and dashboards to monitor sustainability. More tools are being continuously developed.',
    'faq.q8': 'How do I create an account?',
    'faq.a8': 'Click the \'Create Account\' button on the homepage, fill in your details (name, email, and password), and confirm your email. Your account will be ready to use immediately.',
    'faq.q9': 'Is my data secure?',
    'faq.a9': 'Yes, we use end-to-end encryption and follow best data security practices. Your personal data is never shared with third parties without your consent.',
    'faq.q10': 'How do I recover my password?',
    'faq.a10': 'On the login page, click \'Forgot password?\'. Enter your email and you will receive a link to reset your password. The link is valid for 24 hours.',
    'faq.q11': 'Can I delete my account?',
    'faq.a11': 'Yes, you can delete your account at any time in profile settings. All your data will be permanently removed after 30 days.',
    'faq.q12': 'What plans are available?',
    'faq.a12': 'We offer 3 plans: Free (basic resources), Premium (advanced tools), and Enterprise (dedicated consulting). Each plan can be canceled at any time.',
    'faq.q13': 'How do I upgrade?',
    'faq.a13': 'In your account, access \'Plans and Subscription\' and select the desired plan. You will be redirected to the secure payment page. The upgrade is immediate after payment.',
    'faq.q14': 'Do you offer refunds?',
    'faq.a14': 'Yes, we offer a 30-day guarantee. If you are not satisfied, you can request a full refund within that period, no questions asked.',
    'faq.q15': 'What payment methods do you accept?',
    'faq.a15': 'We accept credit cards, bank transfers, and digital wallets. All payments are processed through secure and certified gateways.',
    'faq.q16': 'How do I contact support?',
    'faq.a16': 'You can contact us through the contact form on the website, send an email to support@sustainhub.com, or use the live chat available 24/7.',
    'faq.q17': 'What is the support response time?',
    'faq.a17': 'We respond to all messages within 24 hours. For urgent issues, use the live chat available during business hours.',
    'faq.q18': 'Do you offer training?',
    'faq.a18': 'Yes, we offer free webinars, video tutorials, and complete documentation. Premium customers also have access to personalized training.',

    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.blog': 'Blog',
    'admin.marketplace': 'Marketplace',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.services': 'Services',
    'admin.reports': 'Reports',
    'admin.settings': 'Settings',
    'admin.access_denied': 'Access Restricted',
    'admin.access_denied_msg': 'Only administrators can access this panel.',
    'admin.logged_in_as': 'Logged in as',
    'admin.total_users': 'Total Users',
    'admin.registered': 'Registered',
    'admin.blog_articles': 'Blog Articles',
    'admin.published': 'Published',
    'admin.in_marketplace': 'In Marketplace',
    'admin.services_available': 'Services',
    'admin.available': 'Available',
    'admin.manage_users': 'Manage Users',
    'admin.new_user': 'New User',
    'admin.manage_blog': 'Manage Blog',
    'admin.new_article': 'New Article',
    'admin.manage_marketplace': 'Manage Marketplace',
    'admin.manage_services': 'Manage Services',
    'admin.reports_analytics': 'Reports and Analytics',
    'admin.search_by_name': 'Search by name or email...',
    'admin.search_articles': 'Search articles...',
    'admin.per_page': 'per page',
    'admin.showing': 'Showing',
    'admin.of': 'of',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.actions': 'Actions',
    'admin.title_col': 'Title',
    'admin.author': 'Author',
    'admin.status': 'Status',
    'admin.user': 'User',
    'admin.admin': 'Admin',
    'admin.draft': 'Draft',
    'admin.published_status': 'Published',
    'admin.confirm_delete': 'Are you sure?',
    'admin.new_user_modal': 'New User',
    'admin.edit_user_modal': 'Edit User',
    'admin.full_name': 'Full name',
    'admin.user_role': 'Role',
    'admin.new_article_modal': 'New Article',
    'admin.title_pt': 'Title (PT)',
    'admin.title_en': 'Title (EN)',
    'admin.excerpt_pt': 'Excerpt (PT)',
    'admin.excerpt_en': 'Excerpt (EN)',
    'admin.content_pt': 'Content (PT)',
    'admin.content_en': 'Content (EN)',
    'admin.category': 'Category',
    'admin.image_url': 'Image URL',
    'admin.read_time': 'Read Time (min)',
    'admin.article_status': 'Status',
    'admin.visitors_per_month': 'Visitors per Month',
    'admin.visitor_chart': 'Visitor chart',
    'admin.sales_by_product': 'Sales by Product',
    'admin.sales_chart': 'Sales chart',
    'admin.platform_name': 'Platform Name',
    'admin.contact_email': 'Contact Email',
    'admin.save_changes': 'Save Changes',
    'admin.coming_soon': 'Coming soon...',

    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view_all': 'View All',
    'common.learn_more': 'Learn More',
    'common.get_started': 'Get Started',
    'common.subscribe': 'Subscribe',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    
    // Reviews
    'reviews.error_submit': 'Error submitting review',
    'reviews.login_required': 'Login to rate',
    'reviews.rating_required': 'Select a rating',
    
    // Categories
    'category.seeds': 'Seeds',
    'category.inputs': 'Inputs',
    'category.equipment': 'Equipment',
    'common.info': 'Information',
    'common.no_results': 'No results found for',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.delivery_info': 'Delivery Information',
    'checkout.address': 'Address',
    'checkout.address_placeholder': 'Street, number, neighborhood...',
    'checkout.city': 'City',
    'checkout.city_placeholder': 'Maputo',
    'checkout.phone': 'Phone',
    'checkout.notes': 'Notes',
    'checkout.notes_placeholder': 'Additional delivery instructions...',
    'checkout.payment_method': 'Payment Method',
    'checkout.cash_on_delivery': 'Cash on Delivery',
    'checkout.bank_transfer': 'Bank Transfer',
    'checkout.place_order': 'Place Order',
    'checkout.processing': 'Processing...',
    'checkout.order_summary': 'Order Summary',
    'checkout.total': 'Total',
    'checkout.success': 'Order placed successfully!',
    'checkout.error': 'Error processing order',
    'checkout.empty_cart': 'Empty Cart',
    'checkout.add_products': 'Add products to cart to continue',
    'checkout.go_marketplace': 'Go to Marketplace',
    'checkout.fill_required': 'Please fill all required fields',
    'checkout.payment.cash': 'Cash',
    'checkout.payment.bank_transfer': 'Bank Transfer',

    // Orders
    'orders.my_orders': 'My Orders',
    'orders.order': 'Order',
    'orders.no_orders': 'No Orders',
    'orders.start_shopping': 'Start shopping to see your orders here',
    'orders.login_required': 'Login Required',
    'orders.login_to_view': 'Login to view your orders',
    'orders.delivery_address': 'Delivery Address',
    'orders.payment_method': 'Payment Method',
    'orders.notes': 'Notes',
    'orders.status.pending': 'Pending',
    'orders.status.processing': 'Processing',
    'orders.status.shipped': 'Shipped',
    'orders.status.delivered': 'Delivered',
    'orders.status.cancelled': 'Cancelled',
    'myArea.title': 'My Area',
    'myArea.welcome': 'Welcome',
    'myArea.orders': 'Orders',
    'myArea.profile': 'Profile',
    'myArea.myOrders': 'My Orders',
    'myArea.ordersDescription': 'View your order history',
    'myArea.order': 'Order',
    'myArea.status.pending': 'Pending',
    'myArea.status.processing': 'Processing',
    'myArea.status.shipped': 'Shipped',
    'myArea.status.delivered': 'Delivered',
    'myArea.status.cancelled': 'Cancelled',
    'myArea.deliveryAddress': 'Delivery Address',
    'myArea.phone': 'Phone',
    'myArea.paymentMethod': 'Payment Method',
    'myArea.noOrders': 'You haven\'t placed any orders yet',
    'myArea.goToMarketplace': 'Go to Marketplace',
    'myArea.profileInfo': 'Profile Information',
    'myArea.profileDescription': 'Manage your personal information',
    'myArea.name': 'Name',
    'myArea.email': 'Email',
    'myArea.loginMethod': 'Login Method',
    'myArea.memberSince': 'Member since',

    // Consumer Area
    'consumer.title': 'My Area',
    'consumer.dashboard': 'Dashboard',
    'consumer.blog': 'Blog',
    'consumer.knowledge': 'Knowledge Center',
    'consumer.tools': 'Tools',
    'consumer.marketplace': 'Marketplace',
    'consumer.services': 'Services',
    'consumer.profile': 'Profile',
    'consumer.notifications': 'Notifications',
    'consumer.logout': 'Logout',
    'consumer.editProfile': 'Edit Profile',
    'consumer.profileDesc': 'Manage your personal information',
    'consumer.profilePicture': 'Profile Picture',
    'consumer.changePhoto': 'Change Photo',
    'consumer.personalInfo': 'Personal Information',
    'consumer.personalInfoDesc': 'Update your personal details',
    'consumer.name': 'Name',
    'consumer.email': 'Email',
    'consumer.phone': 'Phone',
    'consumer.address': 'Address',
    'consumer.bio': 'About Me',
    'consumer.saveChanges': 'Save Changes',
    'consumer.cancel': 'Cancel',
    'consumer.notificationPreferences': 'Notification Preferences',
    'consumer.notificationPreferencesDesc': 'Manage how you receive notifications',
    'consumer.emailNotifications': 'Email Notifications',
    'consumer.emailNotificationsDesc': 'Receive updates via email',
    'consumer.orderUpdates': 'Order Updates',
    'consumer.orderUpdatesDesc': 'Notifications about order status',
    'consumer.promotions': 'Promotions and Offers',
    'consumer.promotionsDesc': 'Receive special offers and promotions',
    'consumer.profileUpdated': 'Profile updated successfully',
    'consumer.nameReadOnly': 'Name cannot be changed',
    'consumer.emailReadOnly': 'Email cannot be changed',
    'consumer.photoUpdated': 'Profile picture updated successfully',
    'consumer.invalidImageType': 'Please select a valid image file',
    'consumer.imageTooLarge': 'Image size must be less than 10MB',
    'consumer.compressingImage': 'Compressing image...',
    'consumer.uploadFailed': 'Failed to upload photo',
    'consumer.welcome': 'Welcome back!',
    'consumer.welcomeMessage': 'Here is a summary of your activity',
    'consumer.stats.orders': 'Orders',
    'consumer.stats.articlesRead': 'Articles Read',
    'consumer.stats.services': 'Services',
    'consumer.stats.sustainability': 'Sustainability',
    'consumer.recentOrders': 'Recent Orders',
    'consumer.viewAll': 'View All',
    'consumer.noOrders': 'You haven\'t placed any orders yet',
    'consumer.startShopping': 'Start Shopping',
    'consumer.order': 'Order',
    'consumer.exploreMarketplace': 'Explore Marketplace',
    'consumer.exploreMarketplaceDesc': 'Discover sustainable products',
    'consumer.readArticles': 'Read Articles',
    'consumer.readArticlesDesc': 'Learn about food security',
    'consumer.bookService': 'Book Service',
    'consumer.bookServiceDesc': 'Specialized consultations',
    'consumer.favorites': 'Favorites',

    // Favorites
    'favorites.subtitle': 'Your favorite products and articles',
    'favorites.products': 'Favorite Products',
    'favorites.articles': 'Favorite Articles',
    'favorites.no_products': 'You don\'t have any favorite products yet',
    'favorites.no_articles': 'You don\'t have any favorite articles yet',
    'favorites.browse_products': 'Browse Products',
    'favorites.browse_articles': 'Browse Articles',
    'favorites.removed': 'Removed from favorites',
    'favorites.added': 'Added to favorites',

    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Transforming food systems for a sustainable future in Mozambique',
    'about.mission': 'Our Mission',
    'about.mission_text': 'To promote food and nutritional security in Mozambique through an integrated platform that connects producers, consumers, and experts, facilitating access to knowledge, sustainable products, and consulting services.',
    'about.vision': 'Our Vision',
    'about.vision_text': 'To be the leading food systems transformation platform in Mozambique, recognized for excellence in promoting sustainable practices, technological innovation, and positive social impact in rural and urban communities.',
    'about.story': 'Our Story',
    'about.story_p1': 'SustainHub was born from the urgent need to address food security challenges in Mozambique. Founded in 2024, our platform was created by a team of experts in agriculture, technology, and sustainable development.',
    'about.story_p2': 'Recognizing that food security goes beyond food production, we developed a holistic solution that integrates knowledge, fair trade, specialized consulting, and digital tools to empower farmers and consumers.',
    'about.story_p3': 'Today, we serve thousands of users across Mozambique, connecting local producers to markets, providing education on sustainable practices, and facilitating access to specialized services that transform lives and communities.',
    'about.values_title': 'Our Values',
    'about.values_subtitle': 'Principles that guide every decision and action',
    'about.values.sustainability': 'Sustainability',
    'about.values.sustainability_desc': 'Committed to practices that preserve the environment and ensure resources for future generations',
    'about.values.community': 'Community',
    'about.values.community_desc': 'We strengthen connections between producers, consumers, and experts to create collective impact',
    'about.values.quality': 'Quality',
    'about.values.quality_desc': 'We ensure excellence in products, services, and educational content',
    'about.values.innovation': 'Innovation',
    'about.values.innovation_desc': 'We use technology and creativity to solve complex challenges effectively',
    'about.impact': 'Our Impact',
    'about.stats.users': 'Active Users',
    'about.stats.products': 'Sustainable Products',
    'about.stats.specialists': 'Specialists',
    'about.stats.satisfaction': 'Satisfaction',
    'about.team': 'Our Team',
    'about.team_subtitle': 'Professionals dedicated to transforming food systems',
    'about.team_member_1_name': 'Dinis Matavele',
    'about.team_member_1_role': 'CEO & Founder',
    'about.team_member_1_bio': 'Food security specialist with 10+ years of experience in rural development',
    'about.team_member_2_name': 'Ana Silva',
    'about.team_member_2_role': 'Chief Technology Officer',
    'about.team_member_2_bio': 'Software engineer focused on digital solutions for sustainable agriculture',
    'about.team_member_3_name': 'Carlos Nhaca',
    'about.team_member_3_role': 'Chief Operating Officer',
    'about.team_member_3_bio': 'Agronomist specialized in sustainable practices and value chain management',

    // Welcome Page
    'welcome.title': 'Welcome to SustainHub!',
    'welcome.subtitle': "Let's explore the platform in 4 quick steps",
    'welcome.complete': 'Welcome! Explore the platform.',
    'welcome.skip': 'Skip',
    'welcome.back': 'Back',
    'welcome.next': 'Next',
    'welcome.start': 'Get Started',
    
    'welcome.step1.title': 'Complete Sustainability Platform',
    'welcome.step1.description': 'SustainHub is your central hub for transforming food systems and promoting sustainable practices in Mozambique.',
    'welcome.step1.feature1': 'Access to educational resources and research',
    'welcome.step1.feature2': 'Connection with local experts',
    'welcome.step1.feature3': 'Analysis and planning tools',
    'welcome.step1.feature4': 'Active community of producers',
    
    'welcome.step2.title': 'Sustainable Marketplace',
    'welcome.step2.description': 'Buy and sell local products with transparent sustainability indicators and environmental impact.',
    'welcome.step2.feature1': 'Certified and traceable products',
    'welcome.step2.feature2': 'Sustainability indicators',
    'welcome.step2.feature3': 'Fair and transparent prices',
    'welcome.step2.feature4': 'Fast and secure delivery',
    
    'welcome.step3.title': 'Knowledge Center',
    'welcome.step3.description': 'Access a complete digital library with articles, videos, practical guides and research on sustainable agriculture.',
    'welcome.step3.feature1': 'Technical and scientific articles',
    'welcome.step3.feature2': 'Practical tutorial videos',
    'welcome.step3.feature3': 'Step-by-step guides',
    'welcome.step3.feature4': 'Research and case studies',
    
    'welcome.step4.title': 'Tools and Services',
    'welcome.step4.description': 'Use specialized calculators, analysis dashboards and consult experts to optimize your operations.',
    'welcome.step4.feature1': 'Sustainability calculators',
    'welcome.step4.feature2': 'Analysis dashboards',
    'welcome.step4.feature3': 'Specialized consulting',
    'welcome.step4.feature4': 'Service scheduling',

    // Profile Page
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal information and preferences',
    'profile.personal_info': 'Personal Information',
    'profile.name': 'Name',
    'profile.name_placeholder': 'Enter your full name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.phone_placeholder': '+258 XX XXX XXXX',
    'profile.address': 'Address',
    'profile.address_placeholder': 'Enter your full address',
    'profile.bio': 'Biography',
    'profile.bio_placeholder': 'Tell us a bit about yourself...',
    'profile.language': 'Language',
    'profile.notifications': 'Notification Preferences',
    'profile.email_notifications': 'Email Notifications',
    'profile.email_notifications_desc': 'Receive important updates via email',
    'profile.order_updates': 'Order Updates',
    'profile.order_updates_desc': 'Receive notifications about your orders',
    'profile.promotions': 'Promotions and Offers',
    'profile.promotions_desc': 'Receive special offers and promotions',
    'profile.update_success': 'Profile updated successfully!',
    'profile.update_error': 'Error updating profile',
    'profile.upload_photo': 'Upload Photo',
    'profile.cancel': 'Cancel',
    'profile.photo_upload_success': 'Profile picture updated successfully!',
    'profile.photo_upload_error': 'Error uploading photo',
    'profile.photo_size_error': 'Photo must be less than 5MB',
    'profile.photo_type_error': 'Only images are allowed',

    // Consumer Area (Public)
    'consumerArea.title': 'Consumer Area',
    'consumerArea.subtitle': 'Public content about sustainable agriculture',
    'consumerArea.tabs.blog': 'Blog',
    'consumerArea.tabs.events': 'Events',
    'consumerArea.tabs.news': 'News',
    'consumerArea.noBlog': 'No blog articles available',
    'consumerArea.noEvents': 'No events available',
    'consumerArea.noNews': 'No news available',
    'consumerArea.readMore': 'Read More',
    'consumerArea.viewDetails': 'View Details',
    'consumerArea.eventDate': 'Event Date',
    'consumerArea.eventLocation': 'Location',
    'consumerArea.newsDate': 'News Date',
    'consumerArea.by': 'By',
    'consumerArea.category': 'Category',

    // Services Page
    'services.service1.title': 'Agricultural Technical Consulting',
    'services.service1.description': 'Sustainable agriculture experts to optimize your production',
    'services.service1.feature1': 'Soil analysis',
    'services.service1.feature2': 'Crop planning',
    'services.service1.feature3': 'Resource management',
    'services.service1.price': 'From 2,500 MZN/hour',
    'services.service2.title': 'Sustainability Advisory',
    'services.service2.description': 'Develop sustainable practices and environmental certifications',
    'services.service2.feature1': 'Organic certification',
    'services.service2.feature2': 'Waste management',
    'services.service2.feature3': 'Carbon footprint',
    'services.service2.price': 'From 3,000 MZN/hour',
    'services.service3.title': 'Training and Capacity Building',
    'services.service3.description': 'Practical workshops and courses for your team',
    'services.service3.feature1': 'In-person workshops',
    'services.service3.feature2': 'Online courses',
    'services.service3.feature3': 'Educational materials',
    'services.service3.price': 'From 5,000 MZN/day',
    'services.service4.title': 'Market Analysis',
    'services.service4.description': 'Feasibility studies and commercialization strategies',
    'services.service4.feature1': 'Market research',
    'services.service4.feature2': 'Competitive analysis',
    'services.service4.feature3': 'Business plan',
    'services.service4.price': 'From 4,000 MZN/project',
    'services.schedule_consultation': 'Schedule Consultation',
    'services.need_help': 'Need Personalized Help?',
    'services.team_ready': 'Our team is ready to understand your specific needs',
    'services.chat_online': 'Online Chat',
    'services.chat_response': 'Response in minutes',
    'services.schedule_meeting': 'Schedule Meeting',
    'services.choose_time': 'Choose best time',
    'services.in_person': 'In-Person Visit',
    'services.on_site': 'On-site service',
    'services.contact_us': 'Contact Us',

    // Tools Page
    'tools.tab_carbon': 'Carbon',
    'tools.tab_cost': 'Costs',
    'tools.tab_nutrition': 'Nutrition',
    'tools.carbon.title': 'Carbon Emissions Calculator',
    'tools.carbon.description': 'Estimate CO₂ emissions from your agricultural operation',
    'tools.carbon.area_label': 'Cultivated Area (hectares)',
    'tools.carbon.area_placeholder': 'Ex: 10.5',
    'tools.carbon.fuel_label': 'Fuel Used (liters/month)',
    'tools.carbon.fuel_placeholder': 'Ex: 200',
    'tools.carbon.fertilizer_label': 'Fertilizers (kg/month)',
    'tools.carbon.fertilizer_placeholder': 'Ex: 150',
    'tools.carbon.calculate': 'Calculate Emissions',
    'tools.carbon.result_title': 'Analysis Result',
    'tools.carbon.result_description': 'Your estimated CO₂ emissions',
    'tools.carbon.result_value': 'tons of CO₂/year',
    'tools.carbon.result_info': 'This calculation is an estimate based on agricultural sector averages.',
    'tools.cost.title': 'Production Cost Analysis',
    'tools.cost.description': 'Calculate total costs of your operation',
    'tools.cost.seeds_label': 'Seed Cost (MZN)',
    'tools.cost.seeds_placeholder': 'Ex: 5000',
    'tools.cost.labor_label': 'Labor (MZN)',
    'tools.cost.labor_placeholder': 'Ex: 15000',
    'tools.cost.equipment_label': 'Equipment (MZN)',
    'tools.cost.equipment_placeholder': 'Ex: 8000',
    'tools.cost.calculate': 'Calculate Costs',
    'tools.cost.result_title': 'Estimated Total Cost',
    'tools.cost.result_description': 'Summary of your production costs',
    'tools.cost.result_info': 'This value represents the estimated total cost for the specified period.',
    'tools.nutrition.title': 'Nutritional Calculator',
    'tools.nutrition.description': 'Analyze the nutritional value of your products',
    'tools.nutrition.coming_soon': 'Coming soon',
    'tools.nutrition.info': 'This tool will be available soon to help you calculate the nutritional value of your agricultural products.',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'pt') ? saved : 'pt';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['pt']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
