import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pt: {
    // Header & Navigation
    'nav.home': 'Home',
    'nav.knowledge': 'Centro de Conhecimento',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Serviços',
    'nav.tools': 'Ferramentas',
    'nav.consumer': 'Minha Área',
    'nav.dashboard': 'Minha Área',
    'header.search': 'Buscar...',
    'header.start': 'Começar',
    'header.login': 'Login',
    'header.signup': 'Cadastro',
    'header.logout': 'Sair',
    'header.profile': 'Perfil',
    'header.language': 'Idioma',

    // Hero Section
    'hero.tagline': 'Melhorando a Segurança Alimentar e Segurança Alimentar',
    'hero.title': 'FOOD SHIELD',
    'hero.description': 'A plataforma completa para transformar sistemas alimentares e promover práticas sustentáveis em Moçambique e além',
    'hero.explore': 'Explorar Plataforma',
    'hero.learn_more': 'Saiba Mais',

    // Features Section
    'features.title': 'Tudo Que Você Precisa',
    'features.subtitle': 'Uma plataforma integrada com ferramentas, conhecimento e recursos para impulsionar a sustentabilidade',
    'features.knowledge': 'Centro de Conhecimento',
    'features.knowledge_desc': 'Biblioteca digital com artigos, vídeos, guias e pesquisas sobre agricultura sustentável',
    'features.marketplace': 'Marketplace',
    'features.marketplace_desc': 'Produtos locais com indicadores de sustentabilidade e impacto ambiental',
    'features.consulting': 'Consultoria',
    'features.consulting_desc': 'Especialistas disponíveis para orientar projetos sustentáveis',
    'features.tools': 'Ferramentas Digitais',
    'features.tools_desc': 'Calculadoras e dashboards para análise de sustentabilidade e custos',

    // Stats Section
    'stats.resources': 'Recursos Disponíveis',
    'stats.users': 'Usuários Ativos',
    'stats.specialists': 'Especialistas',
    'stats.satisfaction': 'Satisfação',

    // CTA Section
    'cta.title': 'Pronto Para Começar?',
    'cta.subtitle': 'Junte-se à nossa comunidade e faça parte da transformação sustentável',
    'cta.button': 'Começar Agora',

    // Newsletter Section
    'newsletter.title': 'Fique Atualizado',
    'newsletter.subtitle': 'Receba dicas, notícias e ofertas exclusivas sobre agricultura sustentável',
    'newsletter.email': 'Seu email...',
    'newsletter.subscribe': 'Inscrever',

    // Footer
    'footer.platform': 'Plataforma',
    'footer.resources': 'Recursos',
    'footer.contact': 'Contato',
    'footer.company': 'Empresa',
    'footer.about': 'Sobre Nós',
    'footer.team': 'Equipe',
    'footer.careers': 'Carreiras',
    'footer.partners': 'Parceiros',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.cookies': 'Cookies',
    'footer.accessibility': 'Acessibilidade',

    // Auth
    'auth.login_required': 'Faça login para acessar este recurso',
    'auth.restricted': 'Acesso Restrito',
    'auth.login': 'Fazer Login',

    // Pages
    'page.access_denied': 'Acesso Restrito',
    'page.access_denied_msg': 'Você precisa estar autenticado para acessar esta página.',
    'page.not_found': 'Página Não Encontrada',
    'page.not_found_msg': 'A página que você procura não existe.',

    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Artigos e notícias sobre agricultura sustentável',
    'blog.search_placeholder': 'Buscar artigos...',
    'blog.all_categories': 'Todos',
    'blog.no_results': 'Nenhum artigo encontrado',
    'blog.read_more': 'Ler Mais',
    'blog.by_author': 'Por',
    'blog.read_time': 'min de leitura',

    // Knowledge Center
    'knowledge.title': 'Centro de Conhecimento',
    'knowledge.subtitle': 'Biblioteca digital com recursos sobre agricultura sustentável',
    'knowledge.search_placeholder': 'Buscar recursos...',
    'knowledge.all': 'Todos',
    'knowledge.no_results': 'Nenhum resultado encontrado',

    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.subtitle': 'Produtos locais com indicadores de sustentabilidade',
    'marketplace.filter': 'Filtrar por categoria',
    'marketplace.add_to_cart': 'Adicionar ao Carrinho',
    'marketplace.price': 'Preço',
    'marketplace.stock': 'Em Estoque',
    'marketplace.sustainability': 'Sustentabilidade',
    'marketplace.checkout': 'Finalizar Compra',
    'marketplace.cart_empty': 'Seu carrinho está vazio',
    'marketplace.cart_items': 'itens no carrinho',
    'marketplace.category_all': 'Todos',
    'marketplace.category_seeds': 'Sementes',
    'marketplace.category_inputs': 'Insumos',
    'marketplace.category_equipment': 'Equipamentos',
    'marketplace.category_fresh': 'Produtos Frescos',

    // Services
    'services.title': 'Consultoria',
    'services.subtitle': 'Especialistas disponíveis para orientar seus projetos',
    'services.request': 'Solicitar Consultoria',
    'services.price': 'Preço',
    'services.features': 'Características',
    'services.schedule': 'Agendar Reunião',

    // Tools
    'tools.title': 'Ferramentas Digitais',
    'tools.subtitle': 'Calculadoras e dashboards para análise de sustentabilidade',
    'tools.carbon_calculator': 'Calculadora de Carbono',
    'tools.cost_calculator': 'Calculadora de Custos',
    'tools.calculate': 'Calcular',
    'tools.result': 'Resultado',
    'tools.area_hectares': 'Área (hectares)',
    'tools.fuel_liters': 'Combustível (litros/mês)',
    'tools.fertilizer_kg': 'Fertilizante (kg/mês)',
    'tools.carbon_equivalent': 'Equivalente a:',
    'tools.cost_per_hectare': 'Custo por hectare:',
    'tools.suggested_margin': 'Margem sugerida:',

    // Dashboard
    'dashboard.welcome': 'Bem-vindo',
    'dashboard.activity_summary': 'Aqui está um resumo da sua atividade na plataforma',
    'dashboard.overview': 'Visão Geral',
    'dashboard.purchases': 'Compras',
    'dashboard.consultations': 'Consultorías',
    'dashboard.articles_read': 'Artigos Lidos',
    'dashboard.tools_used': 'Ferramentas Usadas',
    'dashboard.total_spent': 'Total Gasto',
    'dashboard.sustainability_score': 'Pontuação de Sustentabilidade',
    'dashboard.recent_purchases': 'Compras Recentes',
    'dashboard.status_delivered': 'Entregue',
    'dashboard.status_pending': 'Pendente',
    'dashboard.status_scheduled': 'Agendada',
    'dashboard.logout': 'Sair',

    // FAQ
    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Encontre respostas para as dúvidas mais comuns sobre o SustainHub',
    'faq.no_answer': 'Não encontrou sua resposta?',
    'faq.contact_us': 'Entre em contato conosco',

    // Admin Dashboard
    'admin.title': 'Painel de Administração',
    'admin.overview': 'Visão Geral',
    'admin.users': 'Usuários',
    'admin.blog': 'Blog',
    'admin.marketplace': 'Marketplace',
    'admin.products': 'Produtos',
    'admin.orders': 'Pedidos',
    'admin.services': 'Serviços',
    'admin.reports': 'Relatórios',
    'admin.settings': 'Configurações',
    'admin.access_denied': 'Acesso Restrito',
    'admin.access_denied_msg': 'Apenas administradores podem acessar este painel.',
    'admin.logged_in_as': 'Conectado como',
    'admin.total_users': 'Total de Usuários',
    'admin.registered': 'Registrados',
    'admin.blog_articles': 'Artigos de Blog',
    'admin.published': 'Publicados',
    'admin.in_marketplace': 'No Marketplace',
    'admin.services_available': 'Serviços',
    'admin.available': 'Disponíveis',
    'admin.manage_users': 'Gerenciar Usuários',
    'admin.new_user': 'Novo Usuário',
    'admin.manage_blog': 'Gerenciar Blog',
    'admin.new_article': 'Novo Artigo',
    'admin.manage_marketplace': 'Gerenciar Marketplace',
    'admin.manage_services': 'Gerenciar Serviços',
    'admin.reports_analytics': 'Relatórios e Analytics',
    'admin.search_by_name': 'Buscar por nome ou email...',
    'admin.search_articles': 'Buscar artigos...',
    'admin.per_page': 'por página',
    'admin.showing': 'Mostrando',
    'admin.of': 'de',
    'admin.name': 'Nome',
    'admin.email': 'Email',
    'admin.role': 'Função',
    'admin.actions': 'Ações',
    'admin.title_col': 'Título',
    'admin.author': 'Autor',
    'admin.status': 'Status',
    'admin.user': 'Usuário',
    'admin.admin': 'Admin',
    'admin.draft': 'Rascunho',
    'admin.published_status': 'Publicado',
    'admin.confirm_delete': 'Tem certeza?',
    'admin.new_user_modal': 'Novo Usuário',
    'admin.edit_user_modal': 'Editar Usuário',
    'admin.full_name': 'Nome completo',
    'admin.user_role': 'Função',
    'admin.new_article_modal': 'Novo Artigo',
    'admin.title_pt': 'Título (PT)',
    'admin.title_en': 'Título (EN)',
    'admin.excerpt_pt': 'Resumo (PT)',
    'admin.excerpt_en': 'Resumo (EN)',
    'admin.content_pt': 'Conteúdo (PT)',
    'admin.content_en': 'Conteúdo (EN)',
    'admin.category': 'Categoria',
    'admin.image_url': 'URL da Imagem',
    'admin.read_time': 'Tempo de Leitura (min)',
    'admin.article_status': 'Status',
    'admin.visitors_per_month': 'Visitantes por Mês',
    'admin.visitor_chart': 'Gráfico de visitantes',
    'admin.sales_by_product': 'Vendas por Produto',
    'admin.sales_chart': 'Gráfico de vendas',
    'admin.platform_name': 'Nome da Plataforma',
    'admin.contact_email': 'Email de Contato',
    'admin.save_changes': 'Salvar Alterações',
    'admin.coming_soon': 'Em desenvolvimento...',

    // Common
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.sort': 'Ordenar',
    'common.view_all': 'Ver Todas',
    'common.learn_more': 'Saiba Mais',
    'common.get_started': 'Começar',
    'common.subscribe': 'Inscrever',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.delete': 'Deletar',
    'common.edit': 'Editar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Informação',

    // Checkout
    'checkout.title': 'Finalizar Compra',
    'checkout.delivery_info': 'Informações de Entrega',
    'checkout.address': 'Endereço',
    'checkout.address_placeholder': 'Rua, número, bairro...',
    'checkout.city': 'Cidade',
    'checkout.city_placeholder': 'Maputo',
    'checkout.phone': 'Telefone',
    'checkout.notes': 'Observações',
    'checkout.notes_placeholder': 'Instruções adicionais para entrega...',
    'checkout.payment_method': 'Método de Pagamento',
    'checkout.cash_on_delivery': 'Pagamento na Entrega',
    'checkout.bank_transfer': 'Transferência Bancária',
    'checkout.place_order': 'Confirmar Pedido',
    'checkout.processing': 'Processando...',
    'checkout.order_summary': 'Resumo do Pedido',
    'checkout.total': 'Total',
    'checkout.success': 'Pedido realizado com sucesso!',
    'checkout.error': 'Erro ao processar pedido',
    'checkout.empty_cart': 'Carrinho Vazio',
    'checkout.add_products': 'Adicione produtos ao carrinho para continuar',
    'checkout.go_marketplace': 'Ir para Marketplace',
    'checkout.fill_required': 'Preencha todos os campos obrigatórios',
    'checkout.payment.cash': 'Dinheiro',
    'checkout.payment.bank_transfer': 'Transferência Bancária',

    // Orders
    'orders.my_orders': 'Meus Pedidos',
    'orders.order': 'Pedido',
    'orders.no_orders': 'Nenhum Pedido',
    'orders.start_shopping': 'Comece a comprar para ver seus pedidos aqui',
    'orders.login_required': 'Login Necessário',
    'orders.login_to_view': 'Faça login para ver seus pedidos',
    'orders.delivery_address': 'Endereço de Entrega',
    'orders.payment_method': 'Método de Pagamento',
    'orders.notes': 'Observações',
    'orders.status.pending': 'Pendente',
    'orders.status.processing': 'Processando',
    'orders.status.shipped': 'Enviado',
    'orders.status.delivered': 'Entregue',
    'orders.status.cancelled': 'Cancelado',
    'myArea.title': 'Minha Área',
    'myArea.welcome': 'Bem-vindo',
    'myArea.orders': 'Pedidos',
    'myArea.profile': 'Perfil',
    'myArea.myOrders': 'Meus Pedidos',
    'myArea.ordersDescription': 'Veja o histórico dos seus pedidos',
    'myArea.order': 'Pedido',
    'myArea.status.pending': 'Pendente',
    'myArea.status.processing': 'Em Processamento',
    'myArea.status.shipped': 'Enviado',
    'myArea.status.delivered': 'Entregue',
    'myArea.status.cancelled': 'Cancelado',
    'myArea.deliveryAddress': 'Endereço de Entrega',
    'myArea.phone': 'Telefone',
    'myArea.paymentMethod': 'Método de Pagamento',
    'myArea.noOrders': 'Você ainda não fez nenhum pedido',
    'myArea.goToMarketplace': 'Ir para o Marketplace',
    'myArea.profileInfo': 'Informações do Perfil',
    'myArea.profileDescription': 'Gerencie suas informações pessoais',
    'myArea.name': 'Nome',
    'myArea.email': 'Email',
    'myArea.loginMethod': 'Método de Login',
    'myArea.memberSince': 'Membro desde',

    // Consumer Area
    'consumer.title': 'Minha Área',
    'consumer.dashboard': 'Dashboard',
    'consumer.blog': 'Blog',
    'consumer.knowledge': 'Centro de Conhecimento',
    'consumer.tools': 'Ferramentas',
    'consumer.marketplace': 'Marketplace',
    'consumer.services': 'Serviços',
    'consumer.profile': 'Perfil',
    'consumer.notifications': 'Notificações',
    'consumer.logout': 'Sair',
    'consumer.editProfile': 'Editar Perfil',
    'consumer.profileDesc': 'Gerencie suas informações pessoais',
    'consumer.profilePicture': 'Foto de Perfil',
    'consumer.changePhoto': 'Alterar Foto',
    'consumer.personalInfo': 'Informações Pessoais',
    'consumer.personalInfoDesc': 'Atualize seus dados pessoais',
    'consumer.name': 'Nome',
    'consumer.email': 'Email',
    'consumer.phone': 'Telefone',
    'consumer.address': 'Endereço',
    'consumer.bio': 'Sobre Mim',
    'consumer.saveChanges': 'Salvar Alterações',
    'consumer.cancel': 'Cancelar',
    'consumer.notificationPreferences': 'Preferências de Notificação',
    'consumer.notificationPreferencesDesc': 'Gerencie como você recebe notificações',
    'consumer.emailNotifications': 'Notificações por Email',
    'consumer.emailNotificationsDesc': 'Receber atualizações por email',
    'consumer.orderUpdates': 'Atualizações de Pedidos',
    'consumer.orderUpdatesDesc': 'Notificações sobre status de pedidos',
    'consumer.promotions': 'Promoções e Ofertas',
    'consumer.promotionsDesc': 'Receber ofertas especiais e promoções',
    'consumer.profileUpdated': 'Perfil atualizado com sucesso',
    'consumer.nameReadOnly': 'Nome não pode ser alterado',
    'consumer.emailReadOnly': 'Email não pode ser alterado',
    'consumer.photoUpdated': 'Foto de perfil atualizada com sucesso',
    'consumer.invalidImageType': 'Por favor, selecione um arquivo de imagem válido',
    'consumer.imageTooLarge': 'O tamanho da imagem deve ser menor que 10MB',
    'consumer.compressingImage': 'Comprimindo imagem...',
    'consumer.uploadFailed': 'Falha ao fazer upload da foto',
    'consumer.welcome': 'Bem-vindo de volta!',
    'consumer.welcomeMessage': 'Aqui está um resumo da sua atividade',
    'consumer.stats.orders': 'Pedidos',
    'consumer.stats.articlesRead': 'Artigos Lidos',
    'consumer.stats.services': 'Serviços',
    'consumer.stats.sustainability': 'Sustentabilidade',
    'consumer.recentOrders': 'Pedidos Recentes',
    'consumer.viewAll': 'Ver Todos',
    'consumer.noOrders': 'Você ainda não fez nenhum pedido',
    'consumer.startShopping': 'Começar a Comprar',
    'consumer.order': 'Pedido',
    'consumer.exploreMarketplace': 'Explorar Marketplace',
    'consumer.exploreMarketplaceDesc': 'Descubra produtos sustentáveis',
    'consumer.readArticles': 'Ler Artigos',
    'consumer.readArticlesDesc': 'Aprenda sobre segurança alimentar',
    'consumer.bookService': 'Agendar Serviço',
    'consumer.bookServiceDesc': 'Consultorias especializadas',
    'consumer.favorites': 'Favoritos',

    // Favorites
    'favorites.subtitle': 'Seus produtos e artigos favoritos',
    'favorites.products': 'Produtos Favoritos',
    'favorites.articles': 'Artigos Favoritos',
    'favorites.no_products': 'Você ainda não tem produtos favoritos',
    'favorites.no_articles': 'Você ainda não tem artigos favoritos',
    'favorites.browse_products': 'Explorar Produtos',
    'favorites.browse_articles': 'Explorar Artigos',
    'favorites.removed': 'Removido dos favoritos',
    'favorites.added': 'Adicionado aos favoritos',

    // About Page
    'about.title': 'Sobre Nós',
    'about.subtitle': 'Transformando sistemas alimentares para um futuro sustentável em Moçambique',
    'about.mission': 'Nossa Missão',
    'about.mission_text': 'Promover a segurança alimentar e nutricional em Moçambique através de uma plataforma integrada que conecta produtores, consumidores e especialistas, facilitando o acesso a conhecimento, produtos sustentáveis e serviços de consultoria.',
    'about.vision': 'Nossa Visão',
    'about.vision_text': 'Ser a principal plataforma de transformação de sistemas alimentares em Moçambique, reconhecida pela excelência em promover práticas sustentáveis, inovação tecnológica e impacto social positivo nas comunidades rurais e urbanas.',
    'about.story': 'Nossa História',
    'about.story_p1': 'A SustainHub nasceu da necessidade urgente de abordar os desafios de segurança alimentar em Moçambique. Fundada em 2024, nossa plataforma foi criada por uma equipe de especialistas em agricultura, tecnologia e desenvolvimento sustentável.',
    'about.story_p2': 'Reconhecendo que a segurança alimentar vai além da produção de alimentos, desenvolvemos uma solução holística que integra conhecimento, comércio justo, consultoria especializada e ferramentas digitais para empoderar agricultores e consumidores.',
    'about.story_p3': 'Hoje, servimos milhares de usuários em todo Moçambique, conectando produtores locais a mercados, fornecendo educação sobre práticas sustentáveis e facilitando o acesso a serviços especializados que transformam vidas e comunidades.',
    'about.values_title': 'Nossos Valores',
    'about.values_subtitle': 'Princípios que guiam cada decisão e ação',
    'about.values.sustainability': 'Sustentabilidade',
    'about.values.sustainability_desc': 'Comprometidos com práticas que preservam o meio ambiente e garantem recursos para gerações futuras',
    'about.values.community': 'Comunidade',
    'about.values.community_desc': 'Fortalecemos conexões entre produtores, consumidores e especialistas para criar impacto coletivo',
    'about.values.quality': 'Qualidade',
    'about.values.quality_desc': 'Garantimos excelência em produtos, serviços e conteúdo educacional',
    'about.values.innovation': 'Inovação',
    'about.values.innovation_desc': 'Utilizamos tecnologia e criatividade para resolver desafios complexos de forma eficaz',
    'about.impact': 'Nosso Impacto',
    'about.stats.users': 'Usuários Ativos',
    'about.stats.products': 'Produtos Sustentáveis',
    'about.stats.specialists': 'Especialistas',
    'about.stats.satisfaction': 'Satisfação',
    'about.team': 'Nossa Equipe',
    'about.team_subtitle': 'Profissionais dedicados a transformar sistemas alimentares',
    'about.team_member_1_name': 'Dinis Matavele',
    'about.team_member_1_role': 'CEO & Fundador',
    'about.team_member_1_bio': 'Especialista em segurança alimentar com 10+ anos de experiência em desenvolvimento rural',
    'about.team_member_2_name': 'Ana Silva',
    'about.team_member_2_role': 'Diretora de Tecnologia',
    'about.team_member_2_bio': 'Engenheira de software focada em soluções digitais para agricultura sustentável',
    'about.team_member_3_name': 'Carlos Nhaca',
    'about.team_member_3_role': 'Diretor de Operações',
    'about.team_member_3_bio': 'Agrônomo especializado em práticas sustentáveis e gestão de cadeias de valor',

    // Welcome Page
    'welcome.title': 'Bem-vindo ao SustainHub!',
    'welcome.subtitle': 'Vamos conhecer a plataforma em 4 passos rápidos',
    'welcome.complete': 'Bem-vindo! Explore a plataforma.',
    'welcome.skip': 'Pular',
    'welcome.back': 'Voltar',
    'welcome.next': 'Próximo',
    'welcome.start': 'Começar',
    
    'welcome.step1.title': 'Plataforma Completa de Sustentabilidade',
    'welcome.step1.description': 'SustainHub é o seu hub central para transformar sistemas alimentares e promover práticas sustentáveis em Moçambique.',
    'welcome.step1.feature1': 'Acesso a recursos educacionais e pesquisas',
    'welcome.step1.feature2': 'Conexão com especialistas locais',
    'welcome.step1.feature3': 'Ferramentas de análise e planejamento',
    'welcome.step1.feature4': 'Comunidade ativa de produtores',
    
    'welcome.step2.title': 'Marketplace Sustentável',
    'welcome.step2.description': 'Compre e venda produtos locais com indicadores de sustentabilidade e impacto ambiental transparentes.',
    'welcome.step2.feature1': 'Produtos certificados e rastreáveis',
    'welcome.step2.feature2': 'Indicadores de sustentabilidade',
    'welcome.step2.feature3': 'Preços justos e transparentes',
    'welcome.step2.feature4': 'Entrega rápida e segura',
    
    'welcome.step3.title': 'Centro de Conhecimento',
    'welcome.step3.description': 'Acesse uma biblioteca digital completa com artigos, vídeos, guias práticos e pesquisas sobre agricultura sustentável.',
    'welcome.step3.feature1': 'Artigos técnicos e científicos',
    'welcome.step3.feature2': 'Vídeos tutoriais práticos',
    'welcome.step3.feature3': 'Guias passo a passo',
    'welcome.step3.feature4': 'Pesquisas e estudos de caso',
    
    'welcome.step4.title': 'Ferramentas e Serviços',
    'welcome.step4.description': 'Utilize calculadoras especializadas, dashboards de análise e consulte especialistas para otimizar suas operações.',
    'welcome.step4.feature1': 'Calculadoras de sustentabilidade',
    'welcome.step4.feature2': 'Dashboards de análise',
    'welcome.step4.feature3': 'Consultoria especializada',
    'welcome.step4.feature4': 'Agendamento de serviços',

    // Consumer Area (Public)
    'consumerArea.title': 'Área de Consumidor',
    'consumerArea.subtitle': 'Conteúdo público sobre agricultura sustentável',
    'consumerArea.tabs.blog': 'Blog',
    'consumerArea.tabs.events': 'Eventos',
    'consumerArea.tabs.news': 'Notícias',
    'consumerArea.noBlog': 'Nenhum artigo de blog disponível',
    'consumerArea.noEvents': 'Nenhum evento disponível',
    'consumerArea.noNews': 'Nenhuma notícia disponível',
    'consumerArea.readMore': 'Ler Mais',
    'consumerArea.viewDetails': 'Ver Detalhes',
    'consumerArea.eventDate': 'Data do Evento',
    'consumerArea.eventLocation': 'Local',
    'consumerArea.newsDate': 'Data da Notícia',
    'consumerArea.by': 'Por',
    'consumerArea.category': 'Categoria',
  },
  en: {
    // Header & Navigation
    'nav.home': 'Home',
    'nav.knowledge': 'Knowledge Center',
    'nav.marketplace': 'Marketplace',
    'nav.services': 'Services',
    'nav.tools': 'Tools',
    'nav.consumer': 'My Area',
    'nav.dashboard': 'My Area',
    'header.search': 'Search...',
    'header.start': 'Get Started',
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.logout': 'Logout',
    'header.profile': 'Profile',
    'header.language': 'Language',

    // Hero Section
    'hero.tagline': 'Improving Food Safety & Food Security',
    'hero.title': 'FOOD SHIELD',
    'hero.description': 'The complete platform to transform food systems and promote sustainable practices in Mozambique and beyond',
    'hero.explore': 'Explore Platform',
    'hero.learn_more': 'Learn More',

    // Features Section
    'features.title': 'Everything You Need',
    'features.subtitle': 'An integrated platform with tools, knowledge and resources to drive sustainability',
    'features.knowledge': 'Knowledge Center',
    'features.knowledge_desc': 'Digital library with articles, videos, guides and research on sustainable agriculture',
    'features.marketplace': 'Marketplace',
    'features.marketplace_desc': 'Local products with sustainability indicators and environmental impact',
    'features.consulting': 'Consulting',
    'features.consulting_desc': 'Experts available to guide sustainable projects',
    'features.tools': 'Digital Tools',
    'features.tools_desc': 'Calculators and dashboards for sustainability and cost analysis',

    // Stats Section
    'stats.resources': 'Available Resources',
    'stats.users': 'Active Users',
    'stats.specialists': 'Specialists',
    'stats.satisfaction': 'Satisfaction',

    // CTA Section
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Join our community and be part of the sustainable transformation',
    'cta.button': 'Get Started Now',

    // Newsletter Section
    'newsletter.title': 'Stay Updated',
    'newsletter.subtitle': 'Get tips, news and exclusive offers about sustainable agriculture',
    'newsletter.email': 'Your email...',
    'newsletter.subscribe': 'Subscribe',

    // Footer
    'footer.platform': 'Platform',
    'footer.resources': 'Resources',
    'footer.contact': 'Contact',
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.team': 'Team',
    'footer.careers': 'Careers',
    'footer.partners': 'Partners',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookies',
    'footer.accessibility': 'Accessibility',

    // Auth
    'auth.login_required': 'Login to access this resource',
    'auth.restricted': 'Access Restricted',
    'auth.login': 'Login',

    // Pages
    'page.access_denied': 'Access Restricted',
    'page.access_denied_msg': 'You need to be authenticated to access this page.',
    'page.not_found': 'Page Not Found',
    'page.not_found_msg': 'The page you are looking for does not exist.',

    // Blog
    'blog.title': 'Blog',
    'blog.subtitle': 'Articles and news about sustainable agriculture',
    'blog.search_placeholder': 'Search articles...',
    'blog.all_categories': 'All',
    'blog.no_results': 'No articles found',
    'blog.read_more': 'Read More',
    'blog.by_author': 'By',
    'blog.read_time': 'min read',

    // Knowledge Center
    'knowledge.title': 'Knowledge Center',
    'knowledge.subtitle': 'Digital library with resources on sustainable agriculture',
    'knowledge.search_placeholder': 'Search resources...',
    'knowledge.all': 'All',
    'knowledge.no_results': 'No results found',

    // Marketplace
    'marketplace.title': 'Marketplace',
    'marketplace.subtitle': 'Local products with sustainability indicators',
    'marketplace.filter': 'Filter by category',
    'marketplace.add_to_cart': 'Add to Cart',
    'marketplace.price': 'Price',
    'marketplace.stock': 'In Stock',
    'marketplace.sustainability': 'Sustainability',
    'marketplace.checkout': 'Checkout',
    'marketplace.cart_empty': 'Your cart is empty',
    'marketplace.cart_items': 'items in cart',
    'marketplace.category_all': 'All',
    'marketplace.category_seeds': 'Seeds',
    'marketplace.category_inputs': 'Inputs',
    'marketplace.category_equipment': 'Equipment',
    'marketplace.category_fresh': 'Fresh Products',

    // Services
    'services.title': 'Consulting',
    'services.subtitle': 'Experts available to guide your projects',
    'services.request': 'Request Consulting',
    'services.price': 'Price',
    'services.features': 'Features',
    'services.schedule': 'Schedule Meeting',

    // Tools
    'tools.title': 'Digital Tools',
    'tools.subtitle': 'Calculators and dashboards for sustainability analysis',
    'tools.carbon_calculator': 'Carbon Calculator',
    'tools.cost_calculator': 'Cost Calculator',
    'tools.calculate': 'Calculate',
    'tools.result': 'Result',
    'tools.area_hectares': 'Area (hectares)',
    'tools.fuel_liters': 'Fuel (liters/month)',
    'tools.fertilizer_kg': 'Fertilizer (kg/month)',
    'tools.carbon_equivalent': 'Equivalent to:',
    'tools.cost_per_hectare': 'Cost per hectare:',
    'tools.suggested_margin': 'Suggested margin:',

    // Dashboard
    'dashboard.welcome': 'Welcome',
    'dashboard.activity_summary': 'Here is a summary of your activity on the platform',
    'dashboard.overview': 'Overview',
    'dashboard.purchases': 'Purchases',
    'dashboard.consultations': 'Consultations',
    'dashboard.articles_read': 'Articles Read',
    'dashboard.tools_used': 'Tools Used',
    'dashboard.total_spent': 'Total Spent',
    'dashboard.sustainability_score': 'Sustainability Score',
    'dashboard.recent_purchases': 'Recent Purchases',
    'dashboard.status_delivered': 'Delivered',
    'dashboard.status_pending': 'Pending',
    'dashboard.status_scheduled': 'Scheduled',
    'dashboard.logout': 'Logout',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to common questions about SustainHub',
    'faq.no_answer': 'Did not find your answer?',
    'faq.contact_us': 'Contact us',

    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.overview': 'Overview',
    'admin.users': 'Users',
    'admin.blog': 'Blog',
    'admin.marketplace': 'Marketplace',
    'admin.products': 'Products',
    'admin.orders': 'Orders',
    'admin.services': 'Services',
    'admin.reports': 'Reports',
    'admin.settings': 'Settings',
    'admin.access_denied': 'Access Restricted',
    'admin.access_denied_msg': 'Only administrators can access this panel.',
    'admin.logged_in_as': 'Logged in as',
    'admin.total_users': 'Total Users',
    'admin.registered': 'Registered',
    'admin.blog_articles': 'Blog Articles',
    'admin.published': 'Published',
    'admin.in_marketplace': 'In Marketplace',
    'admin.services_available': 'Services',
    'admin.available': 'Available',
    'admin.manage_users': 'Manage Users',
    'admin.new_user': 'New User',
    'admin.manage_blog': 'Manage Blog',
    'admin.new_article': 'New Article',
    'admin.manage_marketplace': 'Manage Marketplace',
    'admin.manage_services': 'Manage Services',
    'admin.reports_analytics': 'Reports and Analytics',
    'admin.search_by_name': 'Search by name or email...',
    'admin.search_articles': 'Search articles...',
    'admin.per_page': 'per page',
    'admin.showing': 'Showing',
    'admin.of': 'of',
    'admin.name': 'Name',
    'admin.email': 'Email',
    'admin.role': 'Role',
    'admin.actions': 'Actions',
    'admin.title_col': 'Title',
    'admin.author': 'Author',
    'admin.status': 'Status',
    'admin.user': 'User',
    'admin.admin': 'Admin',
    'admin.draft': 'Draft',
    'admin.published_status': 'Published',
    'admin.confirm_delete': 'Are you sure?',
    'admin.new_user_modal': 'New User',
    'admin.edit_user_modal': 'Edit User',
    'admin.full_name': 'Full name',
    'admin.user_role': 'Role',
    'admin.new_article_modal': 'New Article',
    'admin.title_pt': 'Title (PT)',
    'admin.title_en': 'Title (EN)',
    'admin.excerpt_pt': 'Excerpt (PT)',
    'admin.excerpt_en': 'Excerpt (EN)',
    'admin.content_pt': 'Content (PT)',
    'admin.content_en': 'Content (EN)',
    'admin.category': 'Category',
    'admin.image_url': 'Image URL',
    'admin.read_time': 'Read Time (min)',
    'admin.article_status': 'Status',
    'admin.visitors_per_month': 'Visitors per Month',
    'admin.visitor_chart': 'Visitor chart',
    'admin.sales_by_product': 'Sales by Product',
    'admin.sales_chart': 'Sales chart',
    'admin.platform_name': 'Platform Name',
    'admin.contact_email': 'Contact Email',
    'admin.save_changes': 'Save Changes',
    'admin.coming_soon': 'Coming soon...',

    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view_all': 'View All',
    'common.learn_more': 'Learn More',
    'common.get_started': 'Get Started',
    'common.subscribe': 'Subscribe',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.delivery_info': 'Delivery Information',
    'checkout.address': 'Address',
    'checkout.address_placeholder': 'Street, number, neighborhood...',
    'checkout.city': 'City',
    'checkout.city_placeholder': 'Maputo',
    'checkout.phone': 'Phone',
    'checkout.notes': 'Notes',
    'checkout.notes_placeholder': 'Additional delivery instructions...',
    'checkout.payment_method': 'Payment Method',
    'checkout.cash_on_delivery': 'Cash on Delivery',
    'checkout.bank_transfer': 'Bank Transfer',
    'checkout.place_order': 'Place Order',
    'checkout.processing': 'Processing...',
    'checkout.order_summary': 'Order Summary',
    'checkout.total': 'Total',
    'checkout.success': 'Order placed successfully!',
    'checkout.error': 'Error processing order',
    'checkout.empty_cart': 'Empty Cart',
    'checkout.add_products': 'Add products to cart to continue',
    'checkout.go_marketplace': 'Go to Marketplace',
    'checkout.fill_required': 'Please fill all required fields',
    'checkout.payment.cash': 'Cash',
    'checkout.payment.bank_transfer': 'Bank Transfer',

    // Orders
    'orders.my_orders': 'My Orders',
    'orders.order': 'Order',
    'orders.no_orders': 'No Orders',
    'orders.start_shopping': 'Start shopping to see your orders here',
    'orders.login_required': 'Login Required',
    'orders.login_to_view': 'Login to view your orders',
    'orders.delivery_address': 'Delivery Address',
    'orders.payment_method': 'Payment Method',
    'orders.notes': 'Notes',
    'orders.status.pending': 'Pending',
    'orders.status.processing': 'Processing',
    'orders.status.shipped': 'Shipped',
    'orders.status.delivered': 'Delivered',
    'orders.status.cancelled': 'Cancelled',
    'myArea.title': 'My Area',
    'myArea.welcome': 'Welcome',
    'myArea.orders': 'Orders',
    'myArea.profile': 'Profile',
    'myArea.myOrders': 'My Orders',
    'myArea.ordersDescription': 'View your order history',
    'myArea.order': 'Order',
    'myArea.status.pending': 'Pending',
    'myArea.status.processing': 'Processing',
    'myArea.status.shipped': 'Shipped',
    'myArea.status.delivered': 'Delivered',
    'myArea.status.cancelled': 'Cancelled',
    'myArea.deliveryAddress': 'Delivery Address',
    'myArea.phone': 'Phone',
    'myArea.paymentMethod': 'Payment Method',
    'myArea.noOrders': 'You haven\'t placed any orders yet',
    'myArea.goToMarketplace': 'Go to Marketplace',
    'myArea.profileInfo': 'Profile Information',
    'myArea.profileDescription': 'Manage your personal information',
    'myArea.name': 'Name',
    'myArea.email': 'Email',
    'myArea.loginMethod': 'Login Method',
    'myArea.memberSince': 'Member since',

    // Consumer Area
    'consumer.title': 'My Area',
    'consumer.dashboard': 'Dashboard',
    'consumer.blog': 'Blog',
    'consumer.knowledge': 'Knowledge Center',
    'consumer.tools': 'Tools',
    'consumer.marketplace': 'Marketplace',
    'consumer.services': 'Services',
    'consumer.profile': 'Profile',
    'consumer.notifications': 'Notifications',
    'consumer.logout': 'Logout',
    'consumer.editProfile': 'Edit Profile',
    'consumer.profileDesc': 'Manage your personal information',
    'consumer.profilePicture': 'Profile Picture',
    'consumer.changePhoto': 'Change Photo',
    'consumer.personalInfo': 'Personal Information',
    'consumer.personalInfoDesc': 'Update your personal details',
    'consumer.name': 'Name',
    'consumer.email': 'Email',
    'consumer.phone': 'Phone',
    'consumer.address': 'Address',
    'consumer.bio': 'About Me',
    'consumer.saveChanges': 'Save Changes',
    'consumer.cancel': 'Cancel',
    'consumer.notificationPreferences': 'Notification Preferences',
    'consumer.notificationPreferencesDesc': 'Manage how you receive notifications',
    'consumer.emailNotifications': 'Email Notifications',
    'consumer.emailNotificationsDesc': 'Receive updates via email',
    'consumer.orderUpdates': 'Order Updates',
    'consumer.orderUpdatesDesc': 'Notifications about order status',
    'consumer.promotions': 'Promotions and Offers',
    'consumer.promotionsDesc': 'Receive special offers and promotions',
    'consumer.profileUpdated': 'Profile updated successfully',
    'consumer.nameReadOnly': 'Name cannot be changed',
    'consumer.emailReadOnly': 'Email cannot be changed',
    'consumer.photoUpdated': 'Profile picture updated successfully',
    'consumer.invalidImageType': 'Please select a valid image file',
    'consumer.imageTooLarge': 'Image size must be less than 10MB',
    'consumer.compressingImage': 'Compressing image...',
    'consumer.uploadFailed': 'Failed to upload photo',
    'consumer.welcome': 'Welcome back!',
    'consumer.welcomeMessage': 'Here is a summary of your activity',
    'consumer.stats.orders': 'Orders',
    'consumer.stats.articlesRead': 'Articles Read',
    'consumer.stats.services': 'Services',
    'consumer.stats.sustainability': 'Sustainability',
    'consumer.recentOrders': 'Recent Orders',
    'consumer.viewAll': 'View All',
    'consumer.noOrders': 'You haven\'t placed any orders yet',
    'consumer.startShopping': 'Start Shopping',
    'consumer.order': 'Order',
    'consumer.exploreMarketplace': 'Explore Marketplace',
    'consumer.exploreMarketplaceDesc': 'Discover sustainable products',
    'consumer.readArticles': 'Read Articles',
    'consumer.readArticlesDesc': 'Learn about food security',
    'consumer.bookService': 'Book Service',
    'consumer.bookServiceDesc': 'Specialized consultations',
    'consumer.favorites': 'Favorites',

    // Favorites
    'favorites.subtitle': 'Your favorite products and articles',
    'favorites.products': 'Favorite Products',
    'favorites.articles': 'Favorite Articles',
    'favorites.no_products': 'You don\'t have any favorite products yet',
    'favorites.no_articles': 'You don\'t have any favorite articles yet',
    'favorites.browse_products': 'Browse Products',
    'favorites.browse_articles': 'Browse Articles',
    'favorites.removed': 'Removed from favorites',
    'favorites.added': 'Added to favorites',

    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Transforming food systems for a sustainable future in Mozambique',
    'about.mission': 'Our Mission',
    'about.mission_text': 'To promote food and nutritional security in Mozambique through an integrated platform that connects producers, consumers, and experts, facilitating access to knowledge, sustainable products, and consulting services.',
    'about.vision': 'Our Vision',
    'about.vision_text': 'To be the leading food systems transformation platform in Mozambique, recognized for excellence in promoting sustainable practices, technological innovation, and positive social impact in rural and urban communities.',
    'about.story': 'Our Story',
    'about.story_p1': 'SustainHub was born from the urgent need to address food security challenges in Mozambique. Founded in 2024, our platform was created by a team of experts in agriculture, technology, and sustainable development.',
    'about.story_p2': 'Recognizing that food security goes beyond food production, we developed a holistic solution that integrates knowledge, fair trade, specialized consulting, and digital tools to empower farmers and consumers.',
    'about.story_p3': 'Today, we serve thousands of users across Mozambique, connecting local producers to markets, providing education on sustainable practices, and facilitating access to specialized services that transform lives and communities.',
    'about.values_title': 'Our Values',
    'about.values_subtitle': 'Principles that guide every decision and action',
    'about.values.sustainability': 'Sustainability',
    'about.values.sustainability_desc': 'Committed to practices that preserve the environment and ensure resources for future generations',
    'about.values.community': 'Community',
    'about.values.community_desc': 'We strengthen connections between producers, consumers, and experts to create collective impact',
    'about.values.quality': 'Quality',
    'about.values.quality_desc': 'We ensure excellence in products, services, and educational content',
    'about.values.innovation': 'Innovation',
    'about.values.innovation_desc': 'We use technology and creativity to solve complex challenges effectively',
    'about.impact': 'Our Impact',
    'about.stats.users': 'Active Users',
    'about.stats.products': 'Sustainable Products',
    'about.stats.specialists': 'Specialists',
    'about.stats.satisfaction': 'Satisfaction',
    'about.team': 'Our Team',
    'about.team_subtitle': 'Professionals dedicated to transforming food systems',
    'about.team_member_1_name': 'Dinis Matavele',
    'about.team_member_1_role': 'CEO & Founder',
    'about.team_member_1_bio': 'Food security specialist with 10+ years of experience in rural development',
    'about.team_member_2_name': 'Ana Silva',
    'about.team_member_2_role': 'Chief Technology Officer',
    'about.team_member_2_bio': 'Software engineer focused on digital solutions for sustainable agriculture',
    'about.team_member_3_name': 'Carlos Nhaca',
    'about.team_member_3_role': 'Chief Operating Officer',
    'about.team_member_3_bio': 'Agronomist specialized in sustainable practices and value chain management',

    // Welcome Page
    'welcome.title': 'Welcome to SustainHub!',
    'welcome.subtitle': "Let's explore the platform in 4 quick steps",
    'welcome.complete': 'Welcome! Explore the platform.',
    'welcome.skip': 'Skip',
    'welcome.back': 'Back',
    'welcome.next': 'Next',
    'welcome.start': 'Get Started',
    
    'welcome.step1.title': 'Complete Sustainability Platform',
    'welcome.step1.description': 'SustainHub is your central hub for transforming food systems and promoting sustainable practices in Mozambique.',
    'welcome.step1.feature1': 'Access to educational resources and research',
    'welcome.step1.feature2': 'Connection with local experts',
    'welcome.step1.feature3': 'Analysis and planning tools',
    'welcome.step1.feature4': 'Active community of producers',
    
    'welcome.step2.title': 'Sustainable Marketplace',
    'welcome.step2.description': 'Buy and sell local products with transparent sustainability indicators and environmental impact.',
    'welcome.step2.feature1': 'Certified and traceable products',
    'welcome.step2.feature2': 'Sustainability indicators',
    'welcome.step2.feature3': 'Fair and transparent prices',
    'welcome.step2.feature4': 'Fast and secure delivery',
    
    'welcome.step3.title': 'Knowledge Center',
    'welcome.step3.description': 'Access a complete digital library with articles, videos, practical guides and research on sustainable agriculture.',
    'welcome.step3.feature1': 'Technical and scientific articles',
    'welcome.step3.feature2': 'Practical tutorial videos',
    'welcome.step3.feature3': 'Step-by-step guides',
    'welcome.step3.feature4': 'Research and case studies',
    
    'welcome.step4.title': 'Tools and Services',
    'welcome.step4.description': 'Use specialized calculators, analysis dashboards and consult experts to optimize your operations.',
    'welcome.step4.feature1': 'Sustainability calculators',
    'welcome.step4.feature2': 'Analysis dashboards',
    'welcome.step4.feature3': 'Specialized consulting',
    'welcome.step4.feature4': 'Service scheduling',

    // Consumer Area (Public)
    'consumerArea.title': 'Consumer Area',
    'consumerArea.subtitle': 'Public content about sustainable agriculture',
    'consumerArea.tabs.blog': 'Blog',
    'consumerArea.tabs.events': 'Events',
    'consumerArea.tabs.news': 'News',
    'consumerArea.noBlog': 'No blog articles available',
    'consumerArea.noEvents': 'No events available',
    'consumerArea.noNews': 'No news available',
    'consumerArea.readMore': 'Read More',
    'consumerArea.viewDetails': 'View Details',
    'consumerArea.eventDate': 'Event Date',
    'consumerArea.eventLocation': 'Location',
    'consumerArea.newsDate': 'News Date',
    'consumerArea.by': 'By',
    'consumerArea.category': 'Category',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('pt');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['pt']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
